### ISSUE TITLE
Migrate JSON-RPC History from SharedPreferences to a table

### ISSUE THREAD

**Issue by chadyj** [WalletConnect/WalletConnectKotlinV2#10]
We need to create a table for all requests, a table for peer responses, and a cross reference table to match up requests with peer responses

**Comment by TalhaAli00** [comment]
Everywhere that the JsonRpcHistory class's `setRequest` method is called, we need to set the response as well. Save Topic D responses in the Relayers resspond `onSuccess` callback. 

DB Fields:
unique id
request id
topic
body
status -> status enum [pending, success, failure]
