### ISSUE TITLE
Chains must not be empty

### ISSUE THREAD

**Issue by Developmc** [WalletConnect/WalletConnectKotlinV2#1096]
**Describe the bug**
The Kotlin sdk internally requires "namespace.chains != null && namespace.chains!!.isEmpty()", but found that for some DApps, the namespace.chains given in the optional may be a null value, causing the sdk to throw an exception: Chains must not be empty。

Note: In earlier versions of sdk, namespace.chains is allowed to be empty. I think it should be compatible with the case where namespace.chains is empty

**SDK Version**
 - Client: [Kotlin]
 - Version [android-bom:1.13.0]

**To Reproduce**
1. Open DApp:  https://debox.pro/anniversary 
2. Click "Connect wallet" -> "Wallet Connect"
3. Use the official test app to scan the code
4. See error ：“Chains must not be empty”

**Screenshots**
![截屏2023-08-16 18 23 16](https://github.com/WalletConnect/WalletConnectKotlinV2/assets/7845973/404d3987-bd0a-429d-9319-40438d78f8e3)

**Comment by jakubuid** [comment]
Hey, thanks for reporting!
Here we can distinguish two rules based on the namespace id:
1. Namespace ID is NOT [CAIP-2 ](https://github.com/ChainAgnostic/CAIPs/blob/main/CAIPs/caip-2.md#syntax) compliant - based on the CAIP-25 chains MUST be defined, cannot be empty
2. Namespace ID is CAIP-2 compliant - based on the CAIp-25 chains can be empty/undefinied

Can you share a session proposal payload that you received from Dapp? So I can see exactly what data is sent

**Comment by Developmc** [comment]
This problem cannot be reproduced now. It should be caused by the DApp modifying the data.
