### ISSUE TITLE
Wrong Metadata fetched from DB when getting Settled Sessions

### ISSUE THREAD

**Issue by TalhaAli00** [WalletConnect/WalletConnectKotlinV2#111]
When calling `SequenceStorageRepository::insertPendingSession` in the `EngineInteractor`,  we are currently inserting the self's Metadata. When `WalletConnectClient::getListOfSettledSessions` is called, the metadata that is returned is always self, never the peers

**Comment by jakobuid** [comment]
It's already fixed. Just merge with develop.
