### ISSUE TITLE
Any reason that WalletConnectKotlinV2 needs repackageclasses in proguard?

### ISSUE THREAD

**Issue by Tlaster** [WalletConnect/WalletConnectKotlinV2#1209]
**Describe the bug**
With repackageclasses in [here](https://github.com/WalletConnect/WalletConnectKotlinV2/blob/1b9339a9c7354987c2458eccfedf175b16710a44/gradle/proguard-rules/sdk-rules.pro#L1) and [here](https://github.com/WalletConnect/WalletConnectKotlinV2/blob/1b9339a9c7354987c2458eccfedf175b16710a44/gradle/consumer-rules/walletconnect-rules.pro#L11) , it will rename all the packages not only from the WalletConnectKotlinV2 SDK but also from other source code, such as the source code from Jetpack.

**SDK Version**
 - Client: Kotlin
 - Version 1.20.0

**To Reproduce**
 - import WalletConnectKotlinV2 SDK
 - build with R8 enable
 - decompile the source code 

**Expected behavior**
WalletConnectKotlinV2 SDK dose not rename packages from other source code.

**Additional context**

**Comment by kacperoak** [comment]
Can you confirm if this is the same on the latest SDK version?

**Comment by marctatham** [comment]
yes, this is 100% the case on the latest SDK version: **1.22.2**

A small extract from the resulting mapping.txt of a minifyEnabled=true build: 
```
com.ethermail.ethermail_android.core.api.model.NonceRequest -> com.walletconnect.rh4:
# {"id":"sourceFile","fileName":"NonceRequest.kt"}
    java.lang.String walletAddress -> a
    1:1:void <init>(java.lang.String):0:0 -> <init>
    1:1:boolean equals(java.lang.Object):0:0 -> equals
    1:1:int hashCode():0:0 -> hashCode
    12:16:java.lang.String toString():0:0 -> toString
      # {"id":"com.android.tools.r8.outlineCallsite","positions":{"1":17,"4":19,"7":22},"outline":"Lcom/walletconnect/i01;e(Ljava/lang/StringBuilder;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;"}
    17:17:java.lang.String toString():0:0 -> toString
    19:19:java.lang.String toString():0:0 -> toString
    22:22:java.lang.String toString():0:0 -> toString
com.ethermail.ethermail_android.core.api.model.NonceResponse -> com.walletconnect.sh4:
# {"id":"sourceFile","fileName":"NonceResponse.kt"}
    
```

Everything is repackaged under `com.walletconnect.` 
Please fix.

**Comment by jakubuid** [comment]
Fixed with BOM_1.31.3
