### ISSUE TITLE
Validatewcuri fun parameter update

### ISSUE THREAD

**Issue by gityms123** [WalletConnect/WalletConnectKotlinV2#125]
I noticed that in the latest validatewcuri method, you must pass the SymKey parameter, that is, the secretkey, but now the parameters of the QR code on the DAPP are all public keys. What should I do

**Comment by jakobuid** [comment]
Hey, to connect a wallet to a Dapp, both apps should support the same walletconnect version. Otherwise, there is no way to connect. To test wc-beta100 kotlin sdk, you can check our kotlin sample apps.

**Comment by samfajargreenlab** [comment]
i got the same issue. I try to pair, but the sdk always returns an invalid wallet uri.

wallet uri i got from demo apps (https://react-app.walletconnect.com/)
```wc:1e9a31fe8859bb33eb93cddb99ae2b1c19eaeb57a7c8f6aee8bf85918dcfd33c@2?relay-protocol=time&symKey=8456aa4af8c997edfea7fa8d266c473151548a37197f7c12524da807f7c12524da807```

but code sdk ```WalletConnectKotlinV2:1.0.0-beta04``` required publicKey, relay

![image](https://user-images.githubusercontent.com/32049051/171272787-41613ed7-f44d-443f-a1c6-8e9aed30f74e.png)
