### ISSUE TITLE
Can't get onSessionRequest Event after pairing.

### ISSUE THREAD

**Issue by 0xfuckcode** [WalletConnect/WalletConnectKotlinV2#128]
Chain:Stellar
I interactived with https://stellarterm.com with this demo.
After I scanned the QR Code generated by stellarterm, and the WalletConnectClient.pair() method was called successfully,I can event got the subscibed Acknowledgement
`
Success(Acknowledgement(id=1650181273141, jsonrpc=2.0, result=SubscriptionIdVO(id=6079995a7811f5a67d852deb1e20fe8c8df488586047818f03ee60917cc0b6df))) topic:TopicVO(value=de3142b93fd74a585ca7b01005749a4f521792b1fe766a25a16bbffa283667c7)
`
And the next step should be triggering the function onSessionProposal(), but nothing happened!

Did I miss any steps after pair() method?

**Comment by jakobuid** [comment]
Hey, what sdk version did you use?
