### ISSUE TITLE
URI Parameter Mismatch publicKey vs symKey & protocol vs relay-protocol

### ISSUE THREAD

**Issue by 0xfuckcode** [WalletConnect/WalletConnectKotlinV2#129]
I generate wallect connect uri on dApp and the content is:
`wc:9dbdb0b7d6dfeefc0a3338de739cafa62925f8f2dd9c65a2d23f82aa33b527f2@2?controller=false&publicKey=57ca24b083858a239b491f6da4e2d7e9e95949d26fa8d84233af725fe6c3525b&relay=%7B%22protocol%22%3A%22waku%22%7D`
Pay attention: The paramters in this uri `publicKey` & `protocol`
Repo path:`walletconnectv2>kotlin>com.walletconnect.walletconnectv2>engine>domain>Validator.kt`
Method validateWCUri() 
Line 96 use the parameter name is `relay-protocol` not `protocol`
Line 103 use the parameter name is `symKey` not `publickKey`
Can anyone told me how to resolve this problem?

**Comment by jakobuid** [comment]
Hey, what Dapp did you use?
Recently, we've been working on some protocol changes, that includes the wc uri change as well. The version with symKey is the one that should be implemented among all platforms.
To connect your wallet with a Dapp, both should support the same protocol version.

**Comment by jakobuid** [comment]
Hey, please use our latest beta-100 release and test it with https://react-app.walletconnect.com/.
