### ISSUE TITLE
Issue with Transaction Signature Resumption after app closure

### ISSUE THREAD

**Issue by ShengXiuyan** [WalletConnect/WalletConnectKotlinV2#1309]
**Description:**
I have encountered an issue regarding the resumption of transaction signature in WalletConnect library version 1.20.0 on the Android operating system. When the app is closed after receiving an incoming onSessionRequest, and then reopened, the incoming request does not automatically repeat. However, if another request is created, the first request is received after the second request. I would like to know how to receive the first request without the need to create additional requests.

**Expected Behavior:**
The app should save and restore the state of requests after app closure and reopening.
Upon reopening the app, the incoming onSessionRequest should automatically repeat without the need to create additional requests.

**Steps to Reproduce:**
Launch the app on the Android operating system.
Receive an incoming onSessionRequest.
Close the app.
Reopen the app.
Observe that the incoming request does not repeat automatically.

**Environment:**
Operating System: Android
WalletConnect Library Version: 1.20.0

I have already reviewed the documentation and usage examples of the WalletConnect library but did not find any information on how to resolve this issue. I would appreciate any assistance in resolving this matter.

**Comment by jakubuid** [comment]
Hey @ShengXiuyan thanks for reporting.
SDK is not designed in a way to receive requests on init that have been already received.
To get all pending requests please use this method:  fun getPendingListOfSessionRequests(topic: String): List<Wallet.Model.SessionRequest> from Web3Wallet SDK
