### ISSUE TITLE
Notifications don't work with enableEncrypted = true

### ISSUE THREAD

**Issue by taras1vovchenko** [WalletConnect/WalletConnectKotlinV2#1317]
**Describe the bug**

**SDK Version**
 - Client - Kotlin
 - Version - any

**To Reproduce**
1. set enableEncrypted = true while Web3Wallet init
2. do any action on dApp

**Expected behavior**
onMessage function triggered from PushMessagingService() with right Message type

**Additional context**
Seems like message couldn't be decoded because of logic inside DecryptSignMessageUseCase

```
override suspend fun decryptNotification(topic: String, message: String, onSuccess: (Core.Model.Message) -> Unit, onFailure: (Throwable) -> Unit) {
        try {
            if (!pushMessageStorage.doesPushMessageExist(sha256(message.toByteArray()))) {
                val decryptedMessageString = codec.decrypt(Topic(topic), message)
                val clientJsonRpc: ClientJsonRpc = serializer.tryDeserialize<ClientJsonRpc>(decryptedMessageString) ?: return onFailure(InvalidSignParamsType())
                val params: ClientParams = serializer.deserialize(clientJsonRpc.method, decryptedMessageString) ?: return onFailure(InvalidSignParamsType())
                val metadata: AppMetaData = metadataRepository.getByTopicAndType(Topic(topic), AppMetaDataType.PEER) ?: return onFailure(InvalidSignParamsType())

                when (params) {
                    is SignParams.SessionProposeParams -> onSuccess(params.toCore(clientJsonRpc.id, topic))
                    is SignParams.SessionRequestParams -> onSuccess(params.toCore(clientJsonRpc.id, topic, metadata))
                    else -> onFailure(InvalidSignParamsType())
                }
            }
        } catch (e: Exception) {
            onFailure(e)
        }
    }
```
Seems like inside if (!pushMessageStorage.doesPushMessageExist(sha256(message.toByteArray()))) condition check should be oposite, without "!", because this condition returns false and decoding is not performing

**Comment by jakubuid** [comment]
Hey @taras1vovchenko for reporting!
Please provide precise steps to reproduce your issue. Do you put your app in the foreground or background? Please list everything to help repro.

**Comment by taras1vovchenko** [comment]
Hey @jakubuid 
Steps to reproduce 
1. Init Web3Wallet in MainActivity/App class
`Web3Wallet.registerDeviceToken(
                        firebaseAccessToken = token,
                        enableEncrypted = false,
                        onSuccess = {},
                        onError = { }
                        )`
2. Connect app to dApp
3. Leave app in foreground
4. Request some function from dApp
5. onSessionRequest from WalletDelegate is triggered, but onMessage from PushMessagingService is not triggered

Without encryption, notifications work, but I get Core.Model.Message.Simple model every time, even if was triggered SessionRequest with desired function

**Comment by jakubuid** [comment]
> onSessionRequest from WalletDelegate is triggered, but onMessage from PushMessagingService is not triggered
onSessionRequest is triggered when a dapp sends a request and your wallet is in the foreground

when your app is backgrounded or killed, then the onMessage from PushMessagingService is triggered, the message is decrypted and returned to your app's messaging service

Can you verify that?

**Comment by taras1vovchenko** [comment]
Yeah, you are right, when app either in background or killed onMessage from PushMessagingService is triggered, the message is decrypted and returned to your app's messaging service with correct Message Type

**Comment by jakubuid** [comment]
That's by design
