### ISSUE TITLE
BouncyCastle bundled with WC contains security vulnerability

### ISSUE THREAD

**Issue by soshial** [WalletConnect/WalletConnectKotlinV2#1323]
**Describe the bug**
Current version of Bouncy Castle `"api"("org.bouncycastle:bcprov-jdk15on:$bouncyCastleVersion")` bundled with `walletconnect-foundation` lib is v1.70 which has a [vulnerability](https://mvnrepository.com/artifact/com.walletconnect/foundation/1.14.2).

***Proposed solution**:
Upgrade to the [latest BouncyCastle version v1.77](https://mvnrepository.com/artifact/org.bouncycastle/bcprov-jdk18on).

**SDK Version**:
 - com.walletconnect » android-core [v1.27.2](https://mvnrepository.com/artifact/com.walletconnect/android-core/1.27.2)
 - com.walletconnect » foundation [v1.14.2](https://mvnrepository.com/artifact/com.walletconnect/foundation/1.14.2)

**Comment by jakubuid** [comment]
Thank you for reporting 🙏 We'll look into it and upgrade the dependency.
