### ISSUE TITLE
SignClient.connect: Metamask does not handle multiple chains in a namespace proposal

### ISSUE THREAD

**Issue by BradMoeller** [WalletConnect/WalletConnectKotlinV2#1325]
**Describe the bug**
If the connection params for the `SignClient.connect` function contains multiple chains in the `Namespace.Proposal` object, metamask fails to respond. Other wallets work properly. I've tested Trust, Rainbow, and Zerion

**SDK Version**
 - native android kotlin application
 - android-core:1.27.2
 - auth:1.25.2
 - sign:2.25.2

**To Reproduce**
1. Call `SignClient.connect(connectParams)` with the following `Sign.Params.Connect`:
```
val requiredNamespaces: Map<String, Sign.Model.Namespace.Proposal> =
    mapOf(
        "eip155" to
            Sign.Model.Namespace.Proposal(
                chains = listOf("eip155:1", "eip155:10"),
                methods = defaultMethods,
                events = defaultEvents
            )
    )
val connectParams = Sign.Params.Connect(
    namespaces = requiredNamespaces,
    optionalNamespaces = null,
    properties = null,
    pairing = pairing
)
```
2. Attempt to use Metamask to handle the resulting uri to see it is not handled
3. Use another wallet to see it working properly
3. execute the same code above, but only send 1 chain in the `chains` field: `chains = listOf("eip155:1"),`
4. Metamask now handles it properly

**Expected behavior**
Metamask should display the connect sheet

**Screenshots**

**Device (please complete the following information):**
 - Device: Pixel 8 pro API 34 emulator, pixel 6 physical
 - OS: API 32, API 34

**Additional context**
Might be a metamask limitation? If so, and it is what it is, what would be the best approach for handling multiple connected networks with metamask?

**Comment by jakubuid** [comment]
Hello @BradMoeller thanks for your question. Yes indeed it's  MM limitation, to overcome this you should put one chain as required and the rest in the optional namespaces. Please check and let me know if it helped you 🙏

**Comment by BradMoeller** [comment]
thank you for the response! Yes, this helped clarify the issue
