### ISSUE TITLE
wallet connect cannot redirect the source application after connecting to the okx wallet

### ISSUE THREAD

**Issue by querli** [WalletConnect/WalletConnectKotlinV2#1380]
**Describe the bug**
Today, I use wallet connect to connect okx wallet. After the connection is successful, I cannot redirect to the original application. The tested okx wallet version v6.64.0 and v6.61.0 cannot be used.
Specifically you watch the video

**SDK Version**
 - Client:  KotlinV2 Demo
 - Version bom 1.31.0

![204_1713866440 video_thumb](https://github.com/WalletConnect/WalletConnectKotlinV2/assets/45426897/a6d1255e-6b20-43f8-b881-cfbd7e23b084)

https://github.com/WalletConnect/WalletConnectKotlinV2/assets/45426897/4f2409b9-fd33-4d63-8c9b-f36e427581c3

**Comment by querli** [comment]
![2031713866435_ pic](https://github.com/WalletConnect/WalletConnectKotlinV2/assets/45426897/e5b02e1c-e87c-4346-9e28-30b8e2156c08)

**Comment by querli** [comment]
@jakubuid What can I do if the OKX authorization connection fails to redirect to the original application?

**Comment by jakubuid** [comment]
This will be fixed by the OKX team
