### ISSUE TITLE
Permit2 support on Wallet Connect?

### ISSUE THREAD

**Issue by ronaldoguedess** [WalletConnect/WalletConnectKotlinV2#1451]
I checked, and I couldn't find the Permit2 function to allow Approve off-chain. 
Is it unavailable for Wallet Connect? It would be great add this feature on the testing dapp.
https://react-app.walletconnect.com/

Which one should I use to achieve what I want? `eth_signTypedData` ?
```
eth_sendTransaction,
personal_sign,
eth_accounts,
eth_requestAccounts,
eth_sendRawTransaction,
eth_sign,
eth_signTransaction,
eth_signTypedData,
eth_signTypedData_v3,
eth_signTypedData_v4;
```

**Comment by xemniz** [comment]
any updates?

**Comment by ronaldoguedess** [comment]
I realized that Permit is not a method but an Ethereum function. You can obtain a Permit using eth_signTypedData_v4. When the dapp sends this, make sure to check if the PrimaryType is Permit.

The problem is that i didn't found any dapp that works with Permit2, just Permit.
