### ISSUE TITLE
Add support for Android SDK 23

### ISSUE THREAD

**Issue by jakobuid** [WalletConnect/WalletConnectKotlinV2#191]
- [ ] Change minSDK to 23
- [ ] Test if code is compatible with sdk 23

**Comment by CyrilNb** [comment]
Just to points out that in your article,  [Beginner Guide to WalletConnect v2.0 Sign Protocol](https://medium.com/walletconnect/beginner-guide-to-walletconnect-v2-0-sign-protocol-for-android-developers-936293e30700), you currently mention the min Android SDK as 23 but not supported (yet).
