### ISSUE TITLE
Plan for Chat MVP

### ISSUE THREAD

**Issue by TalhaAli00** [WalletConnect/WalletConnectKotlinV2#196]

**Comment by Elyniss** [comment]
I will create github issues tomorrow

Chat MVP tasks

- [ ]  Keyserver API
    - [ ]  Register
    - [ ]  Resolve
- [ ]  Chat SDK API
    - [ ]  wc_chatInvite
    - [ ]  …
- [ ]  Message local storage
    - [ ]  Indefinite storage groupped by topics
- [ ]  Typed envelopes
    - [ ]  Get pubKey from encrypted message prefix
- [ ]  Sample chat app
    - [ ]  Invites
    - [ ]  Messages
    - [ ]  Push Notofiactions?
    - [ ]  Leaving
- [ ]  Chat delegate for sample app
    - [ ]  Just like Sign

**Comment by Elyniss** [comment]
Issues created and marked with [Chat MVP](https://github.com/WalletConnect/WalletConnectKotlinV2/milestone/9) milestone
