### ISSUE TITLE
Failed to resolve: com.walletconnect:walletconnectv2:1.0.0-beta01

### ISSUE THREAD

**Issue by nftempire** [WalletConnect/WalletConnectKotlinV2#2]
Gradle just doesn't load the module

**Comment by TalhaAli00** [comment]
@nftempire 
Verify that you have Jitpack added to your list of `repositories` block for your projects and not the `buildscript` block. Then verify that the dependency matches the case exactly since Jitpack is case sensitive. We also re-uploaded the dependency to Jitpack.

**Comment by TayfunCesur** [comment]
Check your settings.gradle, and add `maven { url 'https://jitpack.io' }` in your repositories, Cheers 👋
