### ISSUE TITLE
InterruptedIOException when using manual connection

### ISSUE THREAD

**Issue by jakobuid** [WalletConnect/WalletConnectKotlinV2#211]
When using a manual connection control the InterruptedIOException happens.
Scarlet emits: `OnConnectionFailed(throwable=java.io.InterruptedIOException: timeout)`

**Comment by Elyniss** [comment]
Might be related to recent relay server issues.

**Comment by jakobuid** [comment]
I checked an issue on OnePlus6, Google Pixel 6 and I found no problems. Switching from foreground to background works flawlessly.
