### ISSUE TITLE
Pairing not working on OnePlus phones

### ISSUE THREAD

**Issue by CyrilNb** [WalletConnect/WalletConnectKotlinV2#219]
While trying to connect to [your dApp](https://react-app.walletconnect.com/) with OnePlus phones, it always fails. Also tried with others phones (Google Pixels, Samsung, Android emulator) it always works.

 - Version 1.0.0.-beta101

1. Go to (https://react-app.walletconnect.com/)
2. Click on Ethereum then Connect.
3. Scan QR Code with a OnePlus phone

**Expected behavior**
Would expect the Session proposal callback to work, like it is the case with others phone manufacturer I tried.

**Device (please complete the following information):**
 - Device: OnePlus 8 Pro
 - OS: Android 12
 - Browser Brave
 - Version 1.39.122

**Additional context**

**Comment by jakobuid** [comment]
Hey @CyrilNb we are aware of this issue it's caused by our infrastructure and our team is working to fix that.
We'll let you know once it is resolved.
Thanks.

**Comment by CyrilNb** [comment]
Hi @jakobuid, indeed there is an infrastructure outage but are you sure it is relevant to the fact that the SDK is not working on specific phone models? My tests were on the same timeframe where your infrastructure seemed to work well. But if you say so, no problem!

Just wanted to make sure there is no confusion about my issue, I was not reported here the fact that the dApp is often unavailable. I was already aware of this case (I am from the Spot team).

Thanks anyway.

**Comment by jakobuid** [comment]
Alright thanks for deeper insight. We'll have a look on that for sure.
Have you been able to collect any errors from onError callback in the initialize method?

**Comment by ditzdragos** [comment]
On Pair error: Error(throwable=com.walletconnect.walletconnectv2.core.exceptions.client.WalletConnectException$GenericException: Error trying to create pairing. Validate URI)
    com.walletconnect.walletconnectv2.core.exceptions.client.WalletConnectException$GenericException: Error trying to create pairing. Validate URI
        at com.walletconnect.walletconnectv2.engine.domain.EngineInteractor.pair$walletconnectv2_release(EngineInteractor.kt:149)

**Comment by jakobuid** [comment]
This issues is know and already fixed. It will be available within the next release. Thanks!

**Comment by ditzdragos** [comment]
Thank you!

**Comment by seabornlee** [comment]
> This issues is know and already fixed. It will be available within the next release. Thanks!

Just have the same issue. Looking forward the next release.
