### ISSUE TITLE
Add DNS for artifacts

### ISSUE THREAD

**Issue by TalhaAli00** [WalletConnect/WalletConnectKotlinV2#244]
Once we have #243 completed, we want to have a DNS setup for our dependencies so we developers don't have to use Jitpack's  github url

**Comment by TalhaAli00** [comment]
https://jitpack.io/docs/#custom-domain-name

**Comment by jakobuid** [comment]
com.walletconnect.v2:sign:release_version

**Comment by TalhaAli00** [comment]
we'll probably want to move away from Jitpack as we add more modules. Jitpack is not very good for providing customization of dependencies (having multiple artifacts in a single repo, fully custom DNS names). Here's a guide on how to use MavenCentral https://getstream.io/blog/publishing-libraries-to-mavencentral-2021/
