### ISSUE TITLE
Update CI

### ISSUE THREAD

**Issue by TalhaAli00** [WalletConnect/WalletConnectKotlinV2#262]
The goal is to update our CI to automatically tag with the version based on env variables (potentially being pulled from a rest service) and creating a release when merging from Develop into Master. Also create artifacts for the sample apps.

- [ ] Create env variables for each SDK (Sign, Chat, Auth, Push)
- [ ] Merge develop into Master and then tag Master. Tag will be determined by running a Gradle task for each SDK. Pipeline should determine if a new tag needs to be created based on the previous tag and the current value returned by the Gradle task. 
- [ ] Create a release per new tag
- [ ] Generate an artifact for each updated SDK based on if a new tag was generated. Attach artifact to the appropriate release

**Comment by Elyniss** [comment]
Closed as replaced by #400
