### ISSUE TITLE
SessionRequest.JSONRPCRequest.params is not a JSON after deserialization

### ISSUE THREAD

**Issue by ditzdragos** [WalletConnect/WalletConnectKotlinV2#268]
**Describe the bug**
I receive a json string in a SessionRequest and the internal deserialization of the library converts the string to another format.
Before:
`{"id":1658389421577926,"jsonrpc":"2.0","method":"wc_sessionRequest","params":{"request":{"method":"erd_signTransactions","params":{"transactions":[{"nonce":21,"value":"10000000000000000","receiver":"erd1c542gysqkmfqwwwu7tkuhz8kp9yxkg32gzsuvgmryrs74nhhltzqkna8na","sender":"erd1c542gysqkmfqwwwu7tkuhz8kp9yxkg32gzsuvgmryrs74nhhltzqkna8na","gasPrice":1000000000,"gasLimit":60000000,"data":"Zmlyc3Q=","chainID":"D","version":1},{"nonce":22,"value":"20000000000000000","receiver":"erd1c542gysqkmfqwwwu7tkuhz8kp9yxkg32gzsuvgmryrs74nhhltzqkna8na","sender":"erd1c542gysqkmfqwwwu7tkuhz8kp9yxkg32gzsuvgmryrs74nhhltzqkna8na","gasPrice":1000000000,"gasLimit":60000000,"data":"c2Vjb25k","chainID":"D","version":1},{"nonce":23,"value":"30000000000000000","receiver":"erd1c542gysqkmfqwwwu7tkuhz8kp9yxkg32gzsuvgmryrs74nhhltzqkna8na","sender":"erd1c542gysqkmfqwwwu7tkuhz8kp9yxkg32gzsuvgmryrs74nhhltzqkna8na","gasPrice":1000000000,"gasLimit":60000000,"data":"dGhpcmQ=","chainID":"D","version":1}]}},"chainId":"elrond:D"}}`
And I receive the params strings as:
`{transactions=[{nonce=21.0, value=10000000000000000, receiver=erd1c542gysqkmfqwwwu7tkuhz8kp9yxkg32gzsuvgmryrs74nhhltzqkna8na, sender=erd1c542gysqkmfqwwwu7tkuhz8kp9yxkg32gzsuvgmryrs74nhhltzqkna8na, gasPrice=1.0E9, gasLimit=6.0E7, data=Zmlyc3Q=, chainID=D, version=1.0}, {nonce=22.0, value=20000000000000000, receiver=erd1c542gysqkmfqwwwu7tkuhz8kp9yxkg32gzsuvgmryrs74nhhltzqkna8na, sender=erd1c542gysqkmfqwwwu7tkuhz8kp9yxkg32gzsuvgmryrs74nhhltzqkna8na, gasPrice=1.0E9, gasLimit=6.0E7, data=c2Vjb25k, chainID=D, version=1.0}, {nonce=23.0, value=30000000000000000, receiver=erd1c542gysqkmfqwwwu7tkuhz8kp9yxkg32gzsuvgmryrs74nhhltzqkna8na, sender=erd1c542gysqkmfqwwwu7tkuhz8kp9yxkg32gzsuvgmryrs74nhhltzqkna8na, gasPrice=1.0E9, gasLimit=6.0E7, data=dGhpcmQ=, chainID=D, version=1.0}]}`

**SDK Version**
 - Client: Kotlin
 - Version: 2.0.0-rc.0

**To Reproduce**
1. Receive a list of JSON elements in a JSON array as params
2. Preview the received value in onSessionRequest(sessionRequest: Sign.Model.SessionRequest)

**Expected behavior**
The raw string received from the Dapp
`{"request":{"method":"erd_signTransactions","params":{"transactions":[{"nonce":21,"value":"10000000000000000","receiver":"erd1c542gysqkmfqwwwu7tkuhz8kp9yxkg32gzsuvgmryrs74nhhltzqkna8na","sender":"erd1c542gysqkmfqwwwu7tkuhz8kp9yxkg32gzsuvgmryrs74nhhltzqkna8na","gasPrice":1000000000,"gasLimit":60000000,"data":"Zmlyc3Q=","chainID":"D","version":1},{"nonce":22,"value":"20000000000000000","receiver":"erd1c542gysqkmfqwwwu7tkuhz8kp9yxkg32gzsuvgmryrs74nhhltzqkna8na","sender":"erd1c542gysqkmfqwwwu7tkuhz8kp9yxkg32gzsuvgmryrs74nhhltzqkna8na","gasPrice":1000000000,"gasLimit":60000000,"data":"c2Vjb25k","chainID":"D","version":1},{"nonce":23,"value":"30000000000000000","receiver":"erd1c542gysqkmfqwwwu7tkuhz8kp9yxkg32gzsuvgmryrs74nhhltzqkna8na","sender":"erd1c542gysqkmfqwwwu7tkuhz8kp9yxkg32gzsuvgmryrs74nhhltzqkna8na","gasPrice":1000000000,"gasLimit":60000000,"data":"dGhpcmQ=","chainID":"D","version":1}]}`

**Device (please complete the following information):**
 - Device: Oneplus 6
 - OS: Android 11

**Comment by TalhaWC** [comment]
@ditzdragos we just released RC.1 with a fix for the serializing

**Comment by TalhaAli00** [comment]
@ditzdragos RC.1 was released today with a fix for the serializing
