### ISSUE TITLE
CI/CD

### ISSUE THREAD

**Issue by chadyj** [WalletConnect/WalletConnectKotlinV2#29]
Add CI to the project using Github Actions. Run all tests when pushing new changes to develop and to feature branch.

**Comment by chadyj** [comment]
> Hey @chadyj can I work on this issue?

By all means!

Perhaps @jakobuid or @TalhaAli00 can update the issue with some more details of what we are looking for.  Or you can dive in if you don't mind feedback later.

**Comment by DipayanP007** [comment]
I will start working on it. And if it's possible you can provide provide the details on issue and what you are looking for

**Comment by TalhaAli00** [comment]
The only ideas we've come up with are:
* Run unit tests on merging from a feature branch (feature/branch name) into develop
* Run unit tests and integration tests when merging develop into master. During this step, we also want to bump the tag (i.e 1.0.0-beta01 -> 1.0.0-beta02), create a release for in GitHub and then have Jitpack generate an aar for the release. 

If there is anything else we should add, let us know
