### ISSUE TITLE
Incorrect JSONRPCRequest.params format

### ISSUE THREAD

**Issue by Azkae** [WalletConnect/WalletConnectKotlinV2#296]
Some params received in `JSONRPCRequest.params` are not in the correct format:

**Expected**

For example on method `eth_signTransaction` (https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc#eth_signtransaction), params are sent by the dApp in the following format: 
```
[
  {
    "from": "0x0f364Bac605ba88200ac0c740d5484E6634B59d6",
    "to": "0x0f364Bac605ba88200ac0c740d5484E6634B59d6",
    "data": "0x",
    "nonce": "0x0",
    "gasPrice": "0x4a817c800",
    "gasLimit": "0x5208",
    "value": "0x0"
  }
]
```

Note that `value`, `nonce`, `gas` and `gasPrice` are strings.

**Actual behavior**

But `JSONRPCRequest.params` is in the following format:

```
[
  {
    "from": "0x0f364Bac605ba88200ac0c740d5484E6634B59d6",
    "to": "0x0f364Bac605ba88200ac0c740d5484E6634B59d6",
    "data": "0x",
    "nonce": 0,
    "gasPrice": 20000000000,
    "gasLimit": 21000,
    "value": 0
  }
]
```

`nonce`, `gasPrice`, `gasLimit` and `value` are integers instead of strings, see the documentation here: https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc#eth_signtransaction.

I have not tested it but I suspect this will also cause an issue if `value` exceed a Kotlin Long (2^64) since it can go up to 2^256.

**SDK Version**
 - Client: Kotlin
 - Version `2.0.0-rc.0`

**Comment by TalhaAli00** [comment]
@Azkae RC.1 was released today with a fix for the serializing
