### ISSUE TITLE
Internal Error: mac check in ChaCha20Poly1305 failed + "Invalid Remainder"

### ISSUE THREAD

**Issue by CyrilNb** [WalletConnect/WalletConnectKotlinV2#297]
When responding to a `eth_signTransaction` request your example dApp shown "Failed. Invalid Remainder". But with no error callback from the SDK method `SignClient.respond()`. Then I retry and I got this error directly from the onError() callback:

`Error(throwable=com.walletconnect.sign.core.exceptions.client.WalletConnectException$InternalError: mac check in ChaCha20Poly1305 failed)`

Now every time I quit and relaunch the app, this error is received, even with no interaction from me.

**SDK Version**
 - Version: `2.0.0-rc.0`

**Comment by CyrilNb** [comment]
The two errors might be non-related though and should probably be not included in the same issue.

The main bug here is that when I try to respond to a `eth_signTransaction` (with the latest release`Sign v2.0-rc.1`) your React dApp shows `Invalid Remainder`.

**Comment by jakobuid** [comment]
Hey @CyrilNb thanks for reporting!

If you use the kotlin [sample wallet](https://github.com/WalletConnect/WalletConnectKotlinV2/tree/develop/signSDK/wallet) to connect with a react sample [Dapp](https://react-app.walletconnect.com/), the described behaviour is known to us.
The reason of having "Failed. Invalid Remainder" is that on sample wallet side we don't have yet implemented request signing. The signature that is sent by sample wallet is always hardcoded so the verification fails on the Dapp side. 

The verification of signature happens on Dapp side, so any signature verification error is handled by Dapp internally.
The onError callback from `Sign.respond()` is triggered when an error happens during sending request response on the wallet side.

Do you still get `Error(throwable=com.walletconnect.sign.core.exceptions.client.WalletConnectException$InternalError: mac check in ChaCha20Poly1305 failed)` within v2.0-rc.2? We release a new sdk version pls check if it resolves the error above.

I hope it answers your concerns.
