### ISSUE TITLE
Create copy of interfaces and classes in Foundation

### ISSUE THREAD

**Issue by TalhaAli00** [WalletConnect/WalletConnectKotlinV2#300]
Create a copy of the following files with the listed access modifier:

| File Name        | New Access Modifier | Notes
| ----------- | ----------- | ----------- |
| RelayInterface | | remove @file:JvmSynthetic for now |
| Relay.Model   | | |
| JsonRpcRelay | | |
| RelayClient | | remove @file:JvmSynthetic for now |
| ConnectionType | Public | |
| RelayService | | |
| FlowStreamAdapter | | |
| RelayDTO | | |
| RelayMapper | | |
| SubscriptionIdVO | | removed `VO` suffix |
| SubscriptionIdAdapter | | |
| TopicVO | | removed `VO` suffix |
| TopicAdapter | | |
| TtlVO | | removed `VO` suffix |
| TtlAdapter | | |

**Comment by Elyniss** [comment]
Blocked #299
