### ISSUE TITLE
Created copy of Network files from Sign to Core

### ISSUE THREAD

**Issue by TalhaAli00** [WalletConnect/WalletConnectKotlinV2#316]
| File Name | New Access Modifier | Notes
| ----------- | ----------- | ----------- |
| ConnectionController | Public | Moved |
| ManualConnectionLifecycle | Public | Moved |
| ConnectionEvent | Public | Moved |
| ConnectionType | Public | Moved |

**Comment by trastvolt** [comment]
feature/add_network_and_common_modules
