### ISSUE TITLE
Create copy of Core files from Sign to Core

### ISSUE THREAD

**Issue by TalhaAli00** [WalletConnect/WalletConnectKotlinV2#319]
| File Name | New Access Modifier | Notes
| ----------- | ----------- | ----------- |
| RelayDOJsonRpcResultJsonAdapter | Private | |
| SubscriptionIdAdapter | Private | |
| TopicAdapter | Private | |
| TTLAdapter | Private | |
| WalletConnectClientExceptions | Public sealed class without braces | only class definition |
| PeerError | Public sealed class without braces | only class definition with abstract vals |
| EnvelopeType | Public | | 
| ClientParams | Public | |
| JsonRpcClientSync | Public | |
| SerializableJsonRpc | Public | |
| JsonRpcHistoryVO | Public | Remove the VO suffix |
| JsonRpcHistoryResponseVO | Public | remove the VO suffix |
| ParticipantsVO | Public | Remove the VO suffix |
| WCRequestVO | Public | Remove the VO suffix |
| WCResponseVO | Public | Remove the VO suffix | 
| CommonObjects | Public | everything except ExpiryVO </br> Remove VO suffix |
| IrnParamsVO | Public | Remove VO suffix |
| WalletConnectScope | Public | **maybe we don't copy this and each SDK has it own** |
| Time | Public | |

**Comment by jakobuid** [comment]
In android_core the package name changed from `core` to `common`
