### ISSUE TITLE
Disconnect Pairing

### ISSUE THREAD

**Issue by jakobuid** [WalletConnect/WalletConnectKotlinV2#355]
Extend disconnect method in Sign SDK so that it handles `wc_pairingDelete`

**Comment by TalhaAli00** [comment]
This is now available in [Android Core](https://github.com/WalletConnect/WalletConnectKotlinV2/tree/develop/androidCore).

@CyrilNb The disconnect feature is the Sign SDK disconnects the session. The disconnect in the Android Core SDK will allow you to disconnect the pairing. You can find an explanation of the difference between a session and a pairing [here](https://docs.walletconnect.com/2.0/introduction/glossary)
