### ISSUE TITLE
NoRelayConnectionException: No connection available.

### ISSUE THREAD

**Issue by john990** [WalletConnect/WalletConnectKotlinV2#359]
**Describe the bug**
I have called SignClient.initialize() and SignClient.setDappDelegate(),
then tried to call SignClient.connect() afterwards and got this error.

**SDK Version**
 - Client: Kotlin
 - Version 2.0.0-rc.2

**To Reproduce**
1. SignClient.initialize() and SignClient.setDappDelegate()
2. Call SignClient.connect() 

**Expected behavior**
Get normal pairing uri.

**Screenshots**
![image](https://user-images.githubusercontent.com/5292685/185860150-48f16c4b-e398-46fa-9245-b87acc4c9705.png)

**Device (please complete the following information):**
 - OS: [Android 12]

**Additional context**
My network is normal, here is the code for WalletConnect:

``` kotlin
val initString = Sign.Params.Init(
    application = application,
    relayServerUrl = "wss://relay.walletconnect.com?projectId=${meta.projectId}",
    metadata = Sign.Model.AppMetaData(
        name = meta.name,
        description = meta.description,
        url = meta.url,
        icons = listOf(meta.icon),
        redirect = meta.redirect,
    )
)

SignClient.initialize(initString) { error -> loge(error.throwable) }

SignClient.setDappDelegate(WalletConnectDappDelegate())
```

```kotlin
val namespaces = mapOf(
    "flow" to Sign.Model.Namespace.Proposal(
        chains = listOf("flow:${if (Fcl.isMainnet()) "mainnet" else "testnet"}"),
        methods = listOf("flow_authn", "flow_authz", "flow_user_sign"),
        events = listOf("chainChanged", "accountsChanged"),
        extensions = null
    )
)

val connectParams = Sign.Params.Connect(namespaces = namespaces)

SignClient.connect(connectParams,
    onProposedSequence = { launchDeeplink((it as Sign.Model.ProposedSequence.Pairing).uri) },
    onError = { error ->
        loge(error.throwable)
        continuation.resumeWithException(error.throwable)
    }
)
```

**Comment by john990** [comment]
Hi @jakobuid,
I found a way to fix this problem.
Before:
SignClient.initialize() is called in onCreate of MainActivity, throwing an exception.

After:
Called in Application's onCreate, it works.

Don't know what the difference is.

**Comment by jakobuid** [comment]
Hey @john990, it's great that you found a solution. You're right that it's required to initialize the SDK in the Application's onCreate function and pass the `application` as a parameter to the initialize function from there.
In our [docs](https://docs.walletconnect.com/2.0/kotlin/sign/dapp-usage) we stressed that out: `To initialize the Sign client, create a `Sign.Params.Init` object in the Android Application class.`

What's more, to track the connectivity status we recommend using the `fun onConnectionStateChange(state: Sign.Model.ConnectionState)` which you can find in the Dapp and Wallet delegates.

If you notice that your issue persists, contact us again, we're happy to help.
