### ISSUE TITLE
Wallet signer functionality

### ISSUE THREAD

**Issue by jakubuid** [WalletConnect/WalletConnectKotlinV2#38]
Create a wallet signer that presents the basic signer functionality.
Sample app should show case the basic session request handling, parsing the string object to expected object.
Sample app should present what tools, libraries are recommended for signer functionality.
Code samples of parsing the string to expected json rpc object should be added to ReadMe

**Comment by SangameswaranRS** [comment]
@jakobuid any update on this ? . I'm kinda struggling on this "signing functionality" with web3j.

For personal sign I'm sending the Numeric.toHexString(Sign.signPrefixedMessage(Numeric.fromHexString(the given string jon doe etcc), ecKeyPair))

The react-app.walletconnect.com is kind of saying valid: false for personal sign and sign typed data

**Comment by jakubuid** [comment]
personal_sig was added to wallet sample
