### ISSUE TITLE
Failed to resolve: com.walletconnect:WalletConnectKotlinV2:2.0.0-rc.5

### ISSUE THREAD

**Issue by spectrl** [WalletConnect/WalletConnectKotlinV2#422]
**Describe the bug**
Looks like the latest version wasn't released properly as gradle can't resolve it. Downgrading the version to 2.0.0-rc.4 works.

**Comment by spectrl** [comment]
Turns out the installation instructions on this page are incorrect:
https://docs.walletconnect.com/2.0/kotlin/sign/installation

Using `com.walletconnect:sign:2.0.0-rc.5` works.

**Comment by TalhaAli00** [comment]
Thanks for pointing out the issue with the docs, we'll get it updated
