### ISSUE TITLE
Docs not up-to-date with latest version for Session Disconnect

### ISSUE THREAD

**Issue by CyrilNb** [WalletConnect/WalletConnectKotlinV2#430]
The 'Session Disconnect' part (https://docs.walletconnect.com/2.0/kotlin/sign/wallet-usage#session-disconnect) is not up-to-date with the latest release (currently `rc.5`):

In the doc you mentioned: 

```
val disconnectionReason: String = /*The reason for disconnecting the Session*/
val disconnectionCode: String = /*The code for for disconnecting the Session*/
val sessionTopic: String = /*Topic from the Session*/
For reference use CAIP-25: https://github.com/ChainAgnostic/CAIPs/blob/master/CAIPs/caip-25.md
val disconnectParams = Sign.Params.Disconnect(sessionTopic, disconnectionReason, disconnectionCode)

SignClient.disconnect(disconnectParams) { error -> /*callback for error while disconnecting a session*/ }
```

but in fact the class `Sign.Params.Disconnect` do not have all these params anymore, only the `sessionTopic`.

**Comment by jakobuid** [comment]
Hey @CyrilNb thank you for pointing this out! Indeed, `Sign.Params.Disconnect` accepts only `sessionTopic` as parameter. We'll update our docs asap.

**Comment by CyrilNb** [comment]
No problem, happy to help 👍
