### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by devarogundade** [WalletConnect/WalletConnectKotlinV2#471]
Failed to resolve: com.github.WalletConnect.Scarlet:scarlet:1.0.0

Build error message on installation

**Comment by devarogundade** [comment]
Thanks

**Comment by thanhbinh84** [comment]
I have the same issue 

- Create a sample android app 
- Follow the instruction https://docs.walletconnect.com/2.0/kotlin/sign/installation
- Add maven { url 'https://jitpack.io' } 
- Throw error at the gradle sync step 

`Failed to resolve: com.github.WalletConnect.Scarlet:scarlet:1.0.0`


[AndroidExample.zip](https://github.com/WalletConnect/WalletConnectKotlinV2/files/10388816/AndroidExample.zip)

**Comment by devarogundade** [comment]
pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}
rootProject.name = "App name"
include ':app'



Try this in your settings.gradle file

**Comment by thanhbinh84** [comment]
That works. Thanks
