### ISSUE TITLE
Research Background Decryption of sample payload

### ISSUE THREAD

**Issue by Elyniss** [WalletConnect/WalletConnectKotlinV2#500]

**Comment by jakobuid** [comment]
Summary:
The research includes the behavior of any WalletConnect Kotlin SDK in the FCM background service. The goal was to understand any limitations that occur in the background service when it comes to accessing SDKs database.

There scenarios have been tested:
- app being online
- app being backgrounded
- app being killed

In all three scenarios, the notification message with **[DAYA PAYLOAD](https://firebase.google.com/docs/cloud-messaging/concept-options#data_messages)** was send using a postman with POST request to specific device. Every message was delivered into `onMessageReceived` in the FCM service, that enables to retrieve the encrypted message from notification data payload, call the SDK's `decrypt` method and display decrypted message in the system notification.

There were no issues with writing to and reading from SDK's database.
