### ISSUE TITLE
throwable=kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 2000 ms

### ISSUE THREAD

**Issue by Developmc** [WalletConnect/WalletConnectKotlinV2#507]
**Describe the bug**
After I scan the QR code，I did the following:
```
CoreClient.initialize();
SignClient.initialize();
CoreClient.Pairing.pair(pairingParams) { error -> Log.e(tag(this), error.throwable.stackTraceToString()) }
```
then i get an error：throwable=kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 2000 ms。

**SDK Version**
com.walletconnect:android-core:1.3.0
com.walletconnect:sign:2.1.0

**Comment by TalhaAli00** [comment]
@Developmc, are you calling the initialize functions in the application class or in an Activity/Fragment?

**Comment by Developmc** [comment]
@TalhaAli00 hi，I  initialize functions  in the activity , After initialization, execute "CoreClient.Pairing.pair" immediately

**Comment by Developmc** [comment]
by the way, **CoreClient.initialize()**  takes about 800 millisecond，**SignClient.initialize()** takes about 1000 millisecond. 

so i can't calling the initialize functions in the application class .

**Comment by TalhaAli00** [comment]
The SDKs were designed to be initialized in the Application class to allow for all of the dependencies to load correctly. Can you explain your use-case for why the initialization time is an issue?

**Comment by Developmc** [comment]
ok, i see. 
The reason is as follows：
1. initialize functions takes times (almost 2 seconds), will cause the app to start slowly. 
2.WalletConnect is just a separate module, we want to initialize it when we need it, not immediately. 

so is it possible to calling the initialize functions in activity ?

**Comment by Developmc** [comment]
Something strange:
Test the  **kotlin** demo which provided by "WalletConnectKotlinV2",  initialize functions takes only 500-700 millisecond. But when I integrate into the **java project**，it takes almost 2000 millisecond .  same phone, same network

**Comment by Developmc** [comment]
> Something strange: Test the **kotlin** demo which provided by "WalletConnectKotlinV2", initialize functions takes only 500-700 millisecond. But when I integrate into the **java project**，it takes almost 2000 millisecond . same phone, same network

@TalhaAli00 May i know why ?

**Comment by TalhaAli00** [comment]
@Developmc I'm not sure why the SDK behaves differently in a Java project vs a Kotlin project. The compiled bytecode should be there exact same. 

In terms of the app startup being slow, you could use the [App Startup API](https://developer.android.com/topic/libraries/app-startup).

Also, can you explain more why you want to delay initiation until usage? What about the initialization of the sdk is a blocker besides load time for your use case?

**Comment by Developmc** [comment]
###   About Java project vs Kotlin project
I created a new java project and kotlin project, calling the initialize functions in the application class
```
CoreClient.initialize()
SignClient.initialize()
```
**Both projects take the same amount of time**. 

But something is different：my kotlin demo calling "SignClient.initialize()" takes about 500 millisecond,  "WalletConnectKotlinV2" Demo calling "SignClient.initialize()" takes only 50 - 60 millisecond.  i don't know where the problem is 。This is my [demo](https://github.com/Developmc/WalletConnectV2)

### why delay initiation

1. Slow startup is a major factor，Using **App Startup API** cannot effectively solve
2. For my project, not all users open the app to use **WalletConnectV2**. I am worried that initializing WalletConnectV2 will cause power and memory loss

**Comment by Elyniss** [comment]
Thanks for the feedback. It's really interesting to see Java project behaviour. We added an issue to look into that and another for lazy initialisation.
