### ISSUE TITLE
Remove useless dependency

### ISSUE THREAD

**Issue by stosabon** [WalletConnect/WalletConnectKotlinV2#517]
The problem is with `restEasyJava` dependency. The only usage of this library is `javax.ws.rs.core.UriBuilder`. But under the hood `restEasyJava` uses org.jboss.spec.javax.annotation instead of default javax.annotation and it makes your library incompatible with all projects using default `javax.annotation` So I want to change using of `restEasyJava` to direct `javax.ws.rs` library. Don't see a way how to contribute these changes. I've already checked that it works, all tests are passed.
Don't see any reason to use `org.jboss.resteasy`

**Comment by jakobuid** [comment]
Hey @stosabon can you create a PR with your proposition?

**Comment by stosabon** [comment]
@jakobuid remote: Permission to WalletConnect/WalletConnectKotlinV2.git denied to stosabon. unable to access 'https://github.com/WalletConnect/WalletConnectKotlinV2.git/': The requested URL returned error: 403

**Comment by stosabon** [comment]
@jakobuid
