### ISSUE TITLE
Cannot initialize  connect to websocket

### ISSUE THREAD

**Issue by kecson** [WalletConnect/WalletConnectKotlinV2#538]
**Describe the bug**
In MainActivity ,click a button Cannot initialize connect to websocket. 

**SDK Version**
 - Bom Bom: 1.1.0
 - dependencies {
    implementation(platform("com.walletconnect:android-bom:1.1.0"))
    implementation("com.walletconnect:android-core")
    implementation("com.walletconnect:sign")
}

```
fun initWalletconnect(application: Application) {
    val serverUri =
        "wss://$WALLET_CONNECT_PROD_RELAY_URL?projectId=my projectId"
    "${Thread.currentThread().name}:initWalletconnect $serverUri".debugLog();
    CoreClient.initialize(
        relayServerUrl = serverUri,
        connectionType = ConnectionType.AUTOMATIC,
        application = application,
        metaData = Core.Model.AppMetaData(
            name = "Kotlin Dapp",
            description = "Dapp description",
            url = "example.dapp",
            icons = listOf("https://gblobscdn.gitbook.com/spaces%2F-LJJeCjcLrr53DcT1Ml7%2Favatar.png?alt=media"),
            redirect = "kotlin-dapp-wc:/request"
        )
    )

    val initParams = Sign.Params.Init(core = CoreClient)

    SignClient.initialize(initParams) { error ->
        error.throwable.stackTraceToString().debugLog()
        Timber.e(error.throwable.stackTraceToString())
    }
}
```

init when click the button
```
class MainActivity : AppCompatActivity() {

    private lateinit var binding: ActivityMainBinding

    override fun onCreate(savedInstanceState: Bundle?) {
        WindowCompat.setDecorFitsSystemWindows(window, false)
        super.onCreate(savedInstanceState)
        binding = ActivityMainBinding.inflate(layoutInflater)
        setContentView(binding.root)

        binding.btn1.setOnClickListener {
           // init faild,
            initWalletconnect(application)
        }
        binding.btn2.setOnClickListener {
            createPair()
        }

    }
}
```

**Comment by jakobuid** [comment]
hey, @kecson try to move the whole initialization logic to the Application class of your app instead of calling it in the Activity. One of our requirements to initialize the SDK properly is to call init functions from the Application level.

**Comment by kecson** [comment]
> hey, @kecson try to move the whole initialization logic to the Application class of your app instead of calling it in the Activity. One of our requirements to initialize the SDK properly is to call init functions from the Application level.

Why cannot initialization in the Activity? 
 I want to initialize when I need it.  My DAPP Use WalletConnect once, then I will disconnect it.

When I use  [iOS WalletConnectSwiftV2 ](https://github.com/WalletConnect/WalletConnectSwiftV2), it is succeed when I need it.

**Comment by jakobuid** [comment]
Our recommended way of initializing the SDK is to do it in the Application class, due to the wss lib we use for networking.

However, thanks to the MANUAL connection mode you're able to open and close the connection whenever you want. To follow your use case you can call `CoreClient.Relay.connect {  }` when you need to use the SDK and `CoreClient.Relay.disconnect {  }` when your flow is completed.

Ref: https://docs.walletconnect.com/2.0/kotlin/core/relay

**Comment by kecson** [comment]
> Our recommended way of initializing the SDK is to do it in the Application class, due to the wss lib we use for networking.
> 
> However, thanks to the MANUAL connection mode you're able to open and close the connection whenever you want. To follow your use case you can call `CoreClient.Relay.connect { }` when you need to use the SDK and `CoreClient.Relay.disconnect { }` when your flow is completed.
> 
> Ref: https://docs.walletconnect.com/2.0/kotlin/core/relay

`CoreClient.Relay.connect` doesn't work
