### ISSUE TITLE
Make wallet more event driven

### ISSUE THREAD

**Issue by stosabon** [WalletConnect/WalletConnectKotlinV2#540]
**Is your feature request related to a problem? Please describe.**
It is a bit difficult to handle manual disconnect session from wallet with kotlin.Flow

**Describe the solution you'd like**
I would prefer to send DeletedSession.Success and DeletedSession.Error event once it is disconnected even when it is disconnected from Wallet. This way Wallet Application will be allowed to make actions when session disconnected successfully everytime. Because now the only thing happened after attempt of disconnect is logging
My idea is that this flow should be event driven as it is when disconnection happens from DApp to make it consistent.

<img width="1060" alt="Screenshot 2022-12-20 at 11 53 21" src="https://user-images.githubusercontent.com/27279157/208661210-61bcdeb4-f8de-4207-8eb9-47f791e9f242.png">

**Comment by stosabon** [comment]
The problem of your solution that you try to handle it in UI and send Disconnect UI Event even when it happens with error, so result from rpc is unused this way
<img width="765" alt="Screenshot 2022-12-20 at 11 59 46" src="https://user-images.githubusercontent.com/27279157/208662247-b4c5ce6e-fc50-41d3-8a91-5d371b43070d.png">

**Comment by stosabon** [comment]
I would even move it to bug since delete session from Wallet means nothing, because it is not guaranteed at all that actual session will be deleted

**Comment by stosabon** [comment]
Even better thing came to my mind.
You can invoke onSessionDelete after 3 points:
1. Disconnect from Wallet
2. Disconnect from DApp
3. Session expired
This way wallet always will be up to dated with sessions

**Comment by jakobuid** [comment]
PR with adding onSuccess callbacks: https://github.com/WalletConnect/WalletConnectKotlinV2/pull/558
