### ISSUE TITLE
String.hexToBytes() fails with index out of bounds when used on an uneven length string

### ISSUE THREAD

**Issue by PeterTheOne** [WalletConnect/WalletConnectKotlinV2#544]
**Describe the bug**
String.hexToBytes() fails with index out of bounds when used on an uneven length string. I'm not sure how I managed to call it on an uneven String but somehow it happend.

**SDK Version**
With Bom-1.1.0 and Bom-1.0.1

**Expected behavior**
Give some better Error at least.

**Comment by PeterTheOne** [comment]
This is what ChatGPT has to say about it:

There are a couple of potential issues with this code:

The code does not check whether the input string is a valid hexadecimal string. It assumes that the input string is a hexadecimal string of even length, and that each character in the string is a valid hexadecimal digit (i.e., a digit in the range '0' to '9' or a letter in the range 'a' to 'f' or 'A' to 'F'). If the input string is not a valid hexadecimal string, the code may produce unexpected results.

The code does not handle negative values properly. If the input string represents a negative value in hexadecimal, the code will not convert it to the correct negative value in bytes. Instead, it will convert it to a positive value that is the same as the absolute value of the negative hexadecimal value.

It's worth noting that these issues can be addressed by adding some additional error handling and validation to the code. Here's an example of how the code could be modified to handle these issues:

```
fun String.hexToBytes(): ByteArray {
    // Check that the input string is a valid hexadecimal string of even length
    if (this.length % 2 != 0 || !this.matches(Regex("^[0-9a-fA-F]+$"))) {
        throw IllegalArgumentException("Input string is not a valid hexadecimal string")
    }

    val len = this.length
    val data = ByteArray(len / 2)
    var i = 0

    while (i < len) {
        // Convert the hexadecimal digits to a 16-bit integer
        val value = (Character.digit(this[i], 16) shl 4) + Character.digit(this[i + 1], 16)
        // If the value is greater than or equal to 128, it represents a negative value in two's complement
        if (value >= 128) {
            // Convert the value to a negative value by subtracting 256
            data[i / 2] = (value - 256).toByte()
        } else {
            data[i / 2] = value.toByte()
        }
        i += 2
    }

    return data
}
```

**Comment by jakobuid** [comment]
hey @PeterTheOne thanks for reporting, the output from ChatGPT is insane! 

Can you recall in what use case did you get this error?

**Comment by PeterTheOne** [comment]
I think I somehow passed the wrong parameter to from the wc uri or something.
