### ISSUE TITLE
Cannot approve request

### ISSUE THREAD

**Issue by hiletmis** [WalletConnect/WalletConnectKotlinV2#548]
**Describe the bug**
While trying to approve a session proposal an error occurs.

**Error Message**

> JsonRpcInteractor: Received unknown object type

This is the approval message data; 

> Approve
> (
> proposerPublicKey=PublicKey, 
> namespaces={
> eip155=Session(
> - accounts=[eip155:1:0xAddress], 
> - methods=[eth_sendTransaction, eth_signTransaction, eth_sign, personal_sign, eth_signTypedData], 
> - events=[chainChanged, accountsChanged], 
> - extensions=[])
> }, 
> relayProtocol=irn
> )

**SDK Version**
 - Client: Kotlin
 - Version 1.6.0
 - Android Project is Java

**To Reproduce**
1. Go to https://react-app.walletconnect.com
2. Select Ethereum chain and click on Connect
3. Scan QR
4. Approve proposal

**Expected behavior**
Successful connection establishment.

**UnExpected behavior**
Connection fails but when the page is refreshed an unknown wallet can be seen on previous connections. Clicking the "Unknown Wallet" sends a new connection proposal but connection fails again with the same error. App metadata is already set, so the metadata is not working.

**Comment by hiletmis** [comment]
`        fun sessionSettle(
            requestId: Long,
            proposal: SignParams.SessionProposeParams,
            sessionTopic: Topic,
            pairingTopic: Topic,
        ) {
            val selfPublicKey = crypto.getSelfPublicFromKeyAgreement(sessionTopic)
            val selfParticipant = SessionParticipantVO(selfPublicKey.keyAsHex, selfAppMetaData)
            val sessionExpiry = ACTIVE_SESSION
            val unacknowledgedSession = SessionVO.createUnacknowledgedSession(sessionTopic, proposal, selfParticipant, sessionExpiry, namespaces)

            try {
                sessionStorageRepository.insertSession(unacknowledgedSession, pairingTopic, requestId)
                metadataStorageRepository.insertOrAbortMetadata(sessionTopic, selfAppMetaData, AppMetaDataType.SELF)
                metadataStorageRepository.insertOrAbortMetadata(sessionTopic, proposal.proposer.metadata, AppMetaDataType.PEER)
                val params = proposal.toSessionSettleParams(selfParticipant, sessionExpiry, namespaces)
                val sessionSettle = SignRpc.SessionSettle(id = generateId(), params = params)
                val irnParams = IrnParams(Tags.SESSION_SETTLE, Ttl(FIVE_MINUTES_IN_SECONDS))

                **jsonRpcInteractor.publishJsonRpcRequest(sessionTopic, irnParams, sessionSettle, onFailure = { error -> onFailure(error) })**
            } catch (e: SQLiteException) {
                sessionStorageRepository.deleteSession(sessionTopic)
                // todo: missing metadata deletion. Also check other try catches
                onFailure(e)
            }
        }`


The error fires at selected line

**Comment by Elyniss** [comment]
Could you provide us with a sample payload in JSON format?

**Comment by hiletmis** [comment]
{
    "id": 1671792997919,
    "jsonrpc": "2.0",
    "method": "wc_sessionSettle",
    "params": {
        "relay": {
            "protocol": "irn"
        },
        "controller": {
            "publicKey": "db59666709780c54d8dcc115de18d82006c924f96c3ecd0e66e40c132cfa0b64",
            "metadata": {
                "name": "Enno Wallet",
                "description": "Enno Wallet is a secure, multi-chain crypto wallet and decentralized finance gateway",
                "url": "https://ennowallet.com",
                "icons": ["https://ennowallet.com/assets/ennowallet_icon_ennocash.svg"],
                "redirect": {}
            }
        },
        "namespaces": {
            "eip155": {
                "accounts": ["eip155:1:0x6C2ea434Be6Ba7B56b62AeE27A574e4b39f5dabf"],
                "methods": ["eth_sendTransaction", "eth_signTransaction", "eth_sign", "personal_sign", "eth_signTypedData"],
                "events": ["chainChanged", "accountsChanged"],
                "extension": []
            }
        },
        "expiry": 1672397663
    }
}

**Comment by hiletmis** [comment]
Tried the new release;

    implementation("com.walletconnect:android-core:1.8.0")
    implementation("com.walletconnect:sign:2.6.0")

unfortunately still the same

**Comment by jakobuid** [comment]
Hey @hiletmis!
The error: `JsonRpcInteractor: Received unknown object type` indicates that there's sth wrong when receiving the subscription message not with sending. Could you please double-check and provide all error messages that you face?

Is your project open-source so that I can have a look at your Java implementation?
If your project is not available, can I have a code snipped with the initialization?

**Comment by hiletmis** [comment]
The new release seems to be working.

Thanks.

**Comment by hiletmis** [comment]
As you mentioned before the problem is json response from the dapp. I tried to intercept the json message that I received from the dapp and this is what I get;

{
    "id": 1676888915733,
    "jsonrpc": "2.0",
    "method": "irn_subscription",
    "params": {
        "id": "97e3c549aae5c486084cb10ac5fb3a16900d2aec083e80f9a6f52a1868b54542",
        "data": {
            "topic": "b292ca3c172be2c863225967ad9bdfa8637fe945b05f4ab79ca720e992d3c0b3",
            "message": "AO3WlbJyWYgf2dlmNiWVZvdKZrUrn0xWfb1E+KF/XlhZCKR1H541orGLABq0mlxQpnL1On4IvDltDExYuiAITcDatxCJ2fkreKUurwSgYx/ZaLb+UB+EwehLxQ9x/ScnBqLlQ9kxozOKlEF+h7af/8meZDqSKHpPfjvMKQCMS+6DYqfeAbjJy1Skb/xtMKjixzkkddt1/8LZ0T2mhhP0jbv45b2W2tbt3XHth+IxfeUEcCjh+NtRIsNOM3kpYe4KooV3/BOhShC/csv4IStXp6sLtx7UycEmu3gOikjsH/xcWoBvudbnRT0vzi6ZqAb3Q+F9kGo6Cey7fHPWePPS0kTXeYYlStifuOI9lF8rsxaiESJz06m+oiXA+z+HChn+1DLdz26NBdWUFvoBNs1ENkoVMmkDVFML7kts6zjfYYDcAmYoqbA71d2Hxskpzl7xHw+fuUI+m2bzM2L176w3vuRzDOJ6DBArcHemIf+Gck3IYJtBVN8dnvB/ehshciXpkOaucAInskoLT1etxrzphDlKPPd5ZbWGp5VULQ/0LPjHXjEpM6JsnD1H+df1qdv9Pm/DvoF5kNEMCy+Q9YqZdytUAvFBs8YCNffn4tk76eSDgVz38YOPjfzNM9ND6qvv9KirqeeFQMomplcQ8SrZdh2i5I212IfEpcZGup88U5BxgiFuIU65pcc6qBejMzhRGD5h4fEDRNYuOluNIKi5g3UC6TJCfDJXIhD3YplkeL4OadWahezuJTiSADxyhhTJpOCkcY6YvkK2lLq41x/Zjd1aWrOHnlnuMjtpefa2S8rmYGspTPv4uFsy8aNUih7LeoUZUQ+GO7bZ6jJeomQVlBRBObR7lB9J8yem8ylTNMa/5eIJAIaXspjTcBMJS81ta2Yq7hG4VpKD00U53y1832Nyui1UzBnaAEW3XkWhV3sFpvy/r4cBdit3PLe7RrYklck6p99MlKowLJDv3iwGtU3Wx2Bea4zP7YqYV1jbQ4M6",
            "publishedAt": 1676888915420
        }
    }
}

the response of the official walletconnnect test dapp works properly.

but when trying to connect to another website I get the same error I have mentioned before (JsonRpcInteractor). although the iOS version accepts the same response from the same dapp request. 

I think this is a dapp error but for some other reasons the response is only not acceptable by android sdk.

DApp:
https://swop.fi/exchange

How to connect:
Connect -> Keeper Mobile
