### ISSUE TITLE
Unable to initialize Connect Request using Sample Apps with Real Wallet Apps

### ISSUE THREAD

**Issue by yipeiguan** [WalletConnect/WalletConnectKotlinV2#555]
**Describe the bug**
Whenever I use the deeplink option in a debug version of the wallet apps, I noticed that real wallet applications like MetaMask and Rainbow Wallet will get deeplinked into, but no actions will happen.  There will be no popups to ask me to authorize and essentially the flows die. 

**SDK Version**
//Latest versions
const val BOM_VERSION = "1.2.0"
const val FOUNDATION_VERSION = "1.2.0"
const val CORE_VERSION = "1.7.0"
const val SIGN_VERSION = "2.5.0"
const val AUTH_VERSION = "1.5.0"
const val CHAT_VERSION = "1.0.0-alpha06"
const val WEB_3_WALLET = "1.0.0"

**To Reproduce**
1. I downloaded the WalletConnectKotlinV2 zip and extracted it, opening it in android studio. 
2. I  updated the `CoreClient.initialize` to take in a projectId I registered with the website.
3. Then I installed both the `sign.dapp` and the `sign.wallet` sample apps.
4. I try deeplinking into WCWallet 
5. Gives me an authorization bottom sheet, for which I can then authorize and will navigate back into the Dapp with the connected wallet
6. If I instead decide to deeplink into MetaMask or Rainbow, nothing happens

**Expected behavior**
Metamask or Rainbow should show a request for me to authorize, for which I can then navigate back to the app. 

**Screenshots**

**Device (please complete the following information):**
 - Device: Pixel 4
 - OS: Android 13
 
**Additional context**

**Comment by Elyniss** [comment]
Hi @yipeiguan! Metamask and Rainbow do not currently support V2. Here's a list of compatible wallets: https://explorer.walletconnect.com/?version=2&page=1

**Comment by yipeiguan** [comment]
Thanks for confirming @Elyniss.  Does that mean on March 1st, will dapps that use Wallet Connect V1 stop working?  Or will they continue to work?

**Comment by Elyniss** [comment]
We plan to turn off our V1 Relay Server, which means that any that uses it will stop working

**Comment by NilayTheAndroidGuy** [comment]
I am facing issue right now also with etaMask and Rainbow. The code works perfectly with Trust Wallet. Anything to consider while deeplinking it into Metamask and Rainbow?
