### ISSUE TITLE
Android BOM 1.2.0 isn't published

### ISSUE THREAD

**Issue by kamilargent** [WalletConnect/WalletConnectKotlinV2#561]
**Describe the bug**
The latest published android-bom is 1.1.1 and not 1.2.0. See what's published here: https://mvnrepository.com/artifact/com.walletconnect/android-bom

**SDK Version**
 - Client: Android
 - Version Bom 1.1.1

**To Reproduce**
1. Try to updated the dependency to bom 1.2.0

**Expected behavior**
I am able to download the bom 1.2.0 configuration

**Comment by TalhaAli00** [comment]
@kamilargent Thanks for letting us know. The 1.2.0 release for the BOM is now out. It will be available within the next hour
