### ISSUE TITLE
Include pairing topic in exposed session objects

### ISSUE THREAD

**Issue by jakubuid** [WalletConnect/WalletConnectKotlinV2#618]

**Comment by jemshit** [comment]
What is the current approach to find corresponding `Pairing` object for `Session` object? I want to find `uri` for deeplink for `Session` object after sending a request to wallet?

**Comment by jakubuid** [comment]
To get an active session you can use `getActiveSessionByTopic` method from SignClient or Web3Wallet. The method returns the session where in the AppMetaData there is a redirect field that enables calling app via deeplink when sending and responding session requests.
