### ISSUE TITLE
SessionProposal comes randomly

### ISSUE THREAD

**Issue by SeongHo-Won** [WalletConnect/WalletConnectKotlinV2#623]
**Describe the bug**
SessionProposal comes randomly. For example, sometimes it arrives in less than a second, but sometimes it doesn't come after 10 minutes. Then, if SessionProposal comes, all previous Session Proposal comes.
Also, when SessionProposal doesn't come, when I take an Android log, it says timeout 5000ms

**SDK Version**
package com.walletconnect.web3.wallet.client
import com.walletconnect.android.Core
import com.walletconnect.android.CoreClient
import com.walletconnect.auth.client.Auth
import com.walletconnect.auth.client.AuthClient
import com.walletconnect.sign.client.Sign

**To Reproduce**
  1. Go to https://react-app.walletconnect.com/
  2. Select Ethereum, Polygon, ... EVM  and click on Connect
  3. Scan QR
  4. SessionProposal comes randomly

**Expected behavior**
I want to receive SessionProposal consistently.

**Screenshots**

**Device (please complete the following information):**
 - Device: Galaxy S21 5G
 - OS: [Android 12]

Thanks!

**Comment by jakubuid** [comment]
Hey! I have trouble reproducing this issue. Could you provide more information? I'd love to schedule call to see what's going on :)
