### ISSUE TITLE
Sign sdk init failed for release build apk

### ISSUE THREAD

**Issue by mufaith** [WalletConnect/WalletConnectKotlinV2#628]
**release build init failed**
debug is ok,when i build release  SignClient.initialize failed 

**SDK Version**
 - Client: Kotlin wallet
 - Version  android-core:1.4.0 & com.walletconnect:sign:2.2.0

**To Reproduce**
1.  SignClient.initialize
2. SignClient.initialize
3.

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**
 - Device: [e.g. Pixel]
 - OS: [e.g. Android 12]
 - Browser [e.g. stock browser, chrome]

**Additional context**
 - locked <0x03ecea1a> (a org.koin.core.instance.SingleInstanceFactory)
 at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
 at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:111)
 at org.koin.core.scope.Scope.resolveValue(Scope.kt:255)
 at org.koin.core.scope.Scope.resolveInstance(Scope.kt:242)
 at org.koin.core.scope.Scope.get(Scope.kt:205)
 at com.walletconnect.sign.client.SignProtocol.initialize(SignProtocol.kt:131)
 at com.walletconnect.sign.client.SignClient.initialize(unavailable:12)
 at com.coinhub.wallet.CodeApplication.initSignClient(CodeApplication.java:133)
 at com.coinhub.wallet.CodeApplication.b(CodeApplication.java:35)

**Comment by Elyniss** [comment]
Hey! May I suggest using our latest release? Also instead of using a standalone Sign SDK it's advised to use our Web3Wallet SDK to have more integrations out of the box. 

Currently latest version is ![Maven Central](https://img.shields.io/maven-central/v/com.walletconnect/android-bom)

```gradle
dependencies {
    implementation(platform("com.walletconnect:android-bom:1.4.1"))
    implementation("com.walletconnect:android-core")
    implementation("com.walletconnect:web3wallet")
}
```

Let me know if issue persist after upgrade

**Comment by mufaith** [comment]
@Elyniss    ok, i integrate from u self demo, demo show the integratation with sign, so  I want to know the difference between these two   Thanks

**Comment by TalhaAli00** [comment]
You can see an example of the Web3Wallet integration in our new sample application. Here is the link for the same https://github.com/WalletConnect/WalletConnectKotlinV2/tree/develop/samples/web3wallet

**Comment by mufaith** [comment]
> You can see an example of the Web3Wallet integration in our new sample application. Here is the link for the same https://github.com/WalletConnect/WalletConnectKotlinV2/tree/develop/samples/web3wallet

thanks
