### ISSUE TITLE
Crash when using CoreClient.Pairing.create

### ISSUE THREAD

**Issue by china-mobile2008** [WalletConnect/WalletConnectKotlinV2#650]
**Describe the bug**
Calling CoreClient.Pairing.create crashes my app despite passing an onError callback.

**SDK Version**
 - Client: Kotlin
 - Version CORE SDK 1.9.1
 - SIGN_VERSION = "2.7.1"

**To Reproduce**
1. Open wc  Dapp
2. Select ethereum
3. Click connect
4. See crash

**Expected behavior**
no crash

**Screenshots**

https://user-images.githubusercontent.com/10908640/219027214-434b5373-faab-4d5d-af14-cf9cb7350c58.mp4

**Device (please complete the following information):**
 - Device: HUWEI JEF-AN20
 - OS: Android 10

**Additional context**
```
02-14 20:00:03.356 27314 27314 E AndroidRuntime: java.lang.IllegalStateException: Creating Pairing failed: java.lang.IllegalStateException: Creating Pairing failed: java.lang.IllegalStateException: Creating Pairing failed: com.walletconnect.android.internal.common.exception.NoRelayConnectionException: No connection available
02-14 20:00:03.356 27314 27314 E AndroidRuntime: at com.walletconnect.android.internal.common.json_rpc.domain.JsonRpcInteractor.checkConnectionWorking(JsonRpcInteractor.kt:57)
02-14 20:00:03.356 27314 27314 E AndroidRuntime: at com.walletconnect.android.internal.common.json_rpc.domain.JsonRpcInteractor.subscribe(JsonRpcInteractor.kt:178)
02-14 20:00:03.356 27314 27314 E AndroidRuntime: at com.walletconnect.android.internal.common.model.type.JsonRpcInteractorInterface$DefaultImpls.subscribe$default(JsonRpcInteractorInterface.kt:18)
02-14 20:00:03.356 27314 27314 E AndroidRuntime: at com.walletconnect.android.pairing.engine.domain.PairingEngine.create(PairingEngine.kt:92)
02-14 20:00:03.356 27314 27314 E AndroidRuntime: at com.walletconnect.android.pairing.client.PairingProtocol.create(PairingProtocol.kt:42)
02-14 20:00:03.356 27314 27314 E AndroidRuntime: at com.walletconnect.dapp.ui.connect.ConnectViewModel.connectToWallet(ConnectViewModel.kt:63)
02-14 20:00:03.356 27314 27314 E AndroidRuntime: at com.walletconnect.dapp.ui.connect.ConnectViewModel.connectToWallet$default(ConnectViewModel.kt:57)
02-14 20:00:03.356 27314 27314 E AndroidRuntime: at com.walletconnect.dapp.ui.connect.pairing_generate.PairingGenerationDialogFragment.onViewCreated(PairingGenerationDialogFragment.kt:28)
02-14 20:00:03.356 27314 27314 E AndroidRuntime: at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3128)
02-14 20:00:03.356 27314 27314 E AndroidRuntime: at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:552)
02-14 20:00:03.356 27314 27314 E AndroidRuntime: at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
02-14 20:00:03.356 27314 27314 E AndroidRuntime: at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
02-14 20:00:03.356 27314 27314 E AndroidRuntime: at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1823)
02-14 20:00:03.356 27314 27314 E AndroidRuntime: at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
02-14 20:00:03.356 27314 27314 E AndroidRuntime: at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
02-14 20:00:03.356 27314 27314 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:900)
02-14 20:00:03.356 27314 27314 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:103)
02-14 20:00:03.356 27314 27314 E AndroidRuntime: at android.os.Looper.loop(Looper.java:219)
02-14 20:00:03.356 27314 27314 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:8668)
02-14 20:00:03.356 27314 27314 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
02-14 20:00:03.356 27314 27314 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
02-14 20:00:03.356 27314 27314 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
```

**Comment by DengAnbang** [comment]
我也遇到了这个问题，后面发现这个问题是sdk还没初始化好，你稍等一会儿就好了

**Comment by china-mobile2008** [comment]
@DengAnbang 
            hi, i found the reason, pls change relay.walletconnect.com to relay.walletconnect.org, maybe china region access restricted

**Comment by DengAnbang** [comment]
@china-mobile2008 谢谢

**Comment by augus036** [comment]
> @DengAnbang hi, i found the reason, pls change relay.walletconnect.com to relay.walletconnect.org, maybe china region access restricted

请问下，你跑这个例子deeplink能够正常的拉起钱包连接么，我拉起钱包总是失败

**Comment by DengAnbang** [comment]
@augus036 也许你的钱包，并没有适配v2的版本，而你示例是V2的，协议不一样

**Comment by china-mobile2008** [comment]
> @augus036 也许你的钱包，并没有适配v2的版本，而你示例是V2的，协议不一样
```
pls refer to supported wallet protocols v2 wallet
```
https://explorer.walletconnect.com/?version=2

**Comment by china-mobile2008** [comment]
> @augus036 也许你的钱包，并没有适配v2的版本，而你示例是V2的，协议不一样

Can you open the Beekeeper wallet? Why does it go into waiting mode when I click on authorize btn?

**Comment by DengAnbang** [comment]
> > @augus036 也许你的钱包，并没有适配v2的版本，而你示例是V2的，协议不一样
> 
> Can you open the Beekeeper wallet? Why does it go into waiting mode when I click on authorize btn?

I did not find Beekeeper wallet,but I have tested the Bitkeep wallet, V1 protocol can be used normally, if it is V2 protocol, auth can also be used

**Comment by china-mobile2008** [comment]
> > > @augus036 也许你的钱包，并没有适配v2的版本，而你示例是V2的，协议不一样
> > 
> > 
> > Can you open the Beekeeper wallet? Why does it go into waiting mode when I click on authorize btn?
> 
> I did not find Beekeeper wallet,but I have tested the Bitkeep wallet, V1 protocol can be used normally, if it is V2 protocol, auth can also be used

Hi, which version are you using? I found that the latest official BOM 1.6.0 signature and authorization cannot launch BitKeep wallet, but the signature of BOM 1.4.1 can launch BitKeep, while the authorization cannot and it remains in a waiting state before prompting a connection failure.
