### ISSUE TITLE
sign.dapp cannot connect to wallet (BitKeep, TrustWallet)

### ISSUE THREAD

**Issue by augus036** [WalletConnect/WalletConnectKotlinV2#652]
**Describe the bug**
When I use the deeplink function of the sign.dapp example, the effect of pulling up the wallet is wrong

**To Reproduce**
1. Click connect
2. Click on 'deeplink'
3. jump to wallet 
4. nothing happens with TrustWallrt , BitKeep show "WalletConnect connection failed"

**Screenshots**
connect to BitKeep

![gif_20230215_184738](https://user-images.githubusercontent.com/49502534/219007500-be74b1fa-b151-4b7f-a550-cb80502e615f.gif)

**Comment by china-mobile2008** [comment]
@augus036  can you provide a demo? The official website demo cannot connect to the wallet，ths

**Comment by augus036** [comment]
> ```
> @augus036  can you provide a demo? The official website demo cannot connect to the wallet，ths
> ```
I just use the official sample (path: ./sign/dapp/) without any modification code

**Comment by Chukwulawrence** [comment]
> **Describe the bug**
> When I use the deeplink function of the sign.dapp example, the effect of pulling up the wallet is wrong
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Click connect
> 2. Click on 'deeplink'
> 3. jump to wallet 
> 4. nothing happens with TrustWallrt , BitKeep show "WalletConnect connection failed"
> 
> 
> **Screenshots**
> connect to BitKeep
> 
> ![gif_20230215_184738](https://user-images.githubusercontent.com/49502534/219007500-be74b1fa-b151-4b7f-a550-cb80502e615f.gif)
> 
> 

We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by Chukwulawrence** [comment]
> > ```
> > @augus036  can you provide a demo? The official website demo cannot connect to the wallet，ths
> > ```
> I just use the official sample (path: ./sign/dapp/) without any modification code
> 

We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/7KbQyuY5NoxyrhNz5

**Comment by jakubuid** [comment]
Hey, make sure that the wallet supports WalletConnect V2

**Comment by InitialSupport** [comment]
> ```
> @augus036  can you provide a demo? The official website demo cannot connect to the wallet，ths
> ```

We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/7KbQyuY5NoxyrhNz5

**Comment by jakubuid** [comment]
Discussion on: https://github.com/WalletConnect/WalletConnectKotlinV2/issues/696

**Comment by jakubuid** [comment]
Discussion is continued in https://github.com/orgs/WalletConnect/projects/4/views/1?query=is%3Aopen+sort%3Aupdated-desc&pane=issue&itemId=22596911
