### ISSUE TITLE
getListOfSettledSessions() should also contain pairingTopic

### ISSUE THREAD

**Issue by PeterTheOne** [WalletConnect/WalletConnectKotlinV2#670]
**Is your feature request related to a problem? Please describe.**
As mentioned in [Discord](https://discord.com/channels/492410046307631105/1060712862219247696) we would like to view sessions and pairings grouped together in the UI.

**Describe the solution you'd like**
When I call `SignClient.getListOfSettledSessions()` I'd like to get the `pairingTopic` for each session.

**Describe alternatives you've considered**
The alternative is to remember the pairingTopic from the SessionProposal but then I would need to have another list of Sessions stored within our app and keep it snyced with `SignClient.getListOfSettledSessions()`.

**Additional context**
[Discord](https://discord.com/channels/492410046307631105/1060712862219247696)

**Comment by jakubuid** [comment]
Hey, the pairing topic in session objects is included in the latest release
