### ISSUE TITLE
SignClient.initialize ANR

### ISSUE THREAD

**Issue by ankudryavtsev** [WalletConnect/WalletConnectKotlinV2#673]
**Describe the bug**
An ANR occurs while initializing `SignClient`

**SDK Version**
 - Client: Android BOM
 - Version 1.4.1

**To Reproduce**
Steps to reproduce the behaviour:
1. Call `SignClient.initialize`

**Expected behaviour**
No ANR

**Screenshots**

**Device (please complete the following information):**
<img width="300" alt="Screenshot 2023-02-21 at 16 14 43" src="https://user-images.githubusercontent.com/2745488/220399894-e3f2a17a-5a84-48f7-9c28-af927e9cf196.png">

**Additional context**
[Stacktrace 1](https://github.com/WalletConnect/WalletConnectKotlinV2/files/10795432/im.argent.contractwalletclient_issue_e0ff7a9201b516555ec4f0b8963ba8dd_error_session_63E1315401F500017EE125E493E857B1_DNE_0_v2_stacktrace.txt)
[Stacktrace 2](https://github.com/WalletConnect/WalletConnectKotlinV2/files/10795439/im.argent.contractwalletclient_issue_2e945e0676cd6a01cfc514abe0120b9a_ANR_session_63E7379E034A00015B448CD345A87596_DNE_1_v2_stacktrace.txt)

**Comment by TalhaAli00** [comment]
@ankudryavtsev Thanks for reporting this issue. Can you provide repro steps?

**Comment by ankudryavtsev** [comment]
We call `SignClient.initialize` in `Application.onCreate` so all you need is to launch the app.
It's a production issue but I managed to reproduce it with `ANRWatchDog` with a small timeout.

**Comment by let-it-snow** [comment]
Hello @jakubuid @TalhaAli00. We're experiencing the same issue on the same devices after calling `SignClient.initialize`

This issue has 329 ANR events affecting 141 users.

<img width="402" alt="Screenshot 2023-03-16 at 17 46 57" src="https://user-images.githubusercontent.com/45386272/225595159-e78340de-5e29-4985-b391-eea9f7a66ee3.png">

**Comment by jakubuid** [comment]
To confirm, because I didn't include the PR in the previous comment, did you try this solution: https://github.com/WalletConnect/WalletConnectKotlinV2/pull/675 ?

Our team had trouble with the reproduction.

- Can you share what app are we talking about?
- Can you share a code snippet of how you initialize lib? Or by any chance is your project open source? 
- Is it happening only on Samsung devices?

**Comment by let-it-snow** [comment]
We didn't try this solution: [#675](https://github.com/WalletConnect/WalletConnectKotlinV2/pull/675) because also can't reproduce it. We're getting issue notifications on Firebase in production only.

> Is it happening only on Samsung devices?

No, it happened on other devices too.

> Can you share a code snippet of how you initialize lib? Or by any chance is your project open source?

Yes, we initialize lib like this:
```
class WalletApplication : Application() {
    companion object {
        var wcLibraryIsInitialize: Boolean? = null
    }

    init {
        setupBouncyCastle()
    }

    override fun onCreate() {
        super.onCreate()

        //initialization of other services

        initWC()
    }

    private fun initWC() {
        val serverUrl = "wss://${Constant.WCData.WALLET_CONNECT_URL}?projectId=${"wallet_connect_project_id"}"
        val connectionType = ConnectionType.AUTOMATIC

        try {
            CoreClient.initialize(
                relayServerUrl = serverUrl,
                connectionType = connectionType,
                application = this,
                metaData = getAppMetaData()
            ) { throwable ->
                when (throwable.throwable) {
                    is GenericException -> {
                        //do nothing
                    }
                    else -> {
                        wcLibraryIsInitialize = false
                    }
                }
            }

            if (wcLibraryIsInitialize == null) {
                SignClient.initialize(
                    Sign.Params.Init(core = CoreClient),
                    ::onWCInitializeSuccess
                ) { _ ->
                    wcLibraryIsInitialize = false
                }
            }
        } catch (exc: Exception) {
            wcLibraryIsInitialize = false
            exc.printStackTrace()
        }
    }

    private fun onWCInitializeSuccess() {
        wcLibraryIsInitialize = true
    }


    private fun getAppMetaData(): Core.Model.AppMetaData {
        return Core.Model.AppMetaData(
            name = "app",
            description = "InitDescription",
            url = "url",
            icons = listOf("https://icon.svg/"),
            redirect = "kotlin-wallet-wc:/request"
        )
    }
}
```

> Can you share what app are we talking about?

LOBSTR wallet

**Comment by jakubuid** [comment]
@let-it-snow can you tell if this issue is still there? Did you upgrade to the newest SDK version by any chance? 🙏

**Comment by jakubuid** [comment]
@ankudryavtsev @let-it-snow what dependency injection framework do you use in your Android apps?
