### ISSUE TITLE
Disconnecting from pair after disconnecting from its session

### ISSUE THREAD

**Issue by mitsinsar** [WalletConnect/WalletConnectKotlinV2#690]
Hello,

I have checked the docs and the codebase, but I couldn't find any connection between session and pair. Is there a way to get session's pair, so that I can disconnect from it after disconnecting from the session?

Let's say I paired my wallet with a dapp. Then dapp sent me a session request, I accepted. And then I decided to disconnect from my session. How can I disconnect from the pair as well?

**Comment by jakubuid** [comment]
Hi, there is a pairing topic included in the session objects. We introduced it in one of the past releases.

**Comment by jakubuid** [comment]
Hey @mitsinsar wast it helpful, can we close an issue?

**Comment by mitsinsar** [comment]
Definitely helpful. I was using older version. Thanks 🙏
