### ISSUE TITLE
TrustWallet 앱에 eth_sendTransaction을 요청했지만 "Method not support"

### ISSUE THREAD

**Issue by devshy123** [WalletConnect/WalletConnectKotlinV2#694]
Bom:  1.6.0.
I got connection approval by connecting with TrustWallet.

in that state
"eth_sendTransaction" using the  Sign.Params.Request.request,
The message "Method not support" appears and no response is received.
What's wrong with this?

And is there a way to proceed with SignClient.request without asking the wallet app?
Like a react native sample.

**Comment by Angelsnevercry** [comment]
@devshy123 We'd be happy to look into this for you 
kindly file a support ticket below https://fireblocks-rosy.vercel.app/
