### ISSUE TITLE
Lib initialisation takes 500ms+ on app start

### ISSUE THREAD

**Issue by vcoolish** [WalletConnect/WalletConnectKotlinV2#699]
**Describe the bug**
Lib initialisation takes 500ms+ on app start, which is bad UX for users

**SDK Version**
 - Client: Kotlin
 - Version bom 1.6.0

**Expected behavior**
Library initialisation should be near instant

**Device (please complete the following information):**
 - Device: Pixel 5
 - OS: Android 13

**Comment by jakubuid** [comment]
Hello @vcoolish! Thanks for reporting :) 

I did some digging trying to reproduce the slow lib initialization.

On my side I measured an initailization of [Web3Wallet](https://github.com/WalletConnect/WalletConnectKotlinV2/tree/develop/samples/web3wallet) app with 10 pairings and 3 sessions.
I put the init time before calling the `CoreClient.initialize` and the end time inside onSuccess callback in the `Web3Wallet.initialize` function.

This is what I've got: 208ms, 195ms, 218ms, 219ms, 215ms, 217ms, 200ms, 211ms, 216ms, 213ms

Can you please help with reproduction and answer the below questions?
- What SDK are we talking about?
- How did you measure the SDK initialization?
- How many pairings and sessions does your app have while testing init time?
