### ISSUE TITLE
Support CAIPs `account_address`/`asset_reference` max length increase

### ISSUE THREAD

**Issue by RobertoArtiles** [WalletConnect/WalletConnectKotlinV2#709]
**Describe the bug**

Atm, they are [hardcoded](https://github.com/WalletConnect/WalletConnectKotlinV2/blob/develop/androidCore/sdk/src/main/kotlin/com/walletconnect/android/internal/utils/CoreValidator.kt#L38-L39) to 32 and 64 characters respectively. With this [PR](https://github.com/ChainAgnostic/CAIPs/pull/179) the max has changed to 128 characters for both.

**Comment by jakubuid** [comment]
Hey, thanks for the heads-up.
Since you're right about the account_address length in the CAIP-25, the reference remains the same which is a part of the[ CAIP-2](https://chainagnostic.org/CAIPs/caip-2)
The CAIP-10 consist of CAIP-2
