### ISSUE TITLE
Why this restriction on the namespace name?

### ISSUE THREAD

**Issue by stKhaDgar** [WalletConnect/WalletConnectKotlinV2#717]
**Problem**
We are trying to add support for **everscale** blockchain, but it does not go through your **NAMESPACE_REGEX** because it is limited to 8 characters, according to the regular line (everscale name contains 9). Why is this needed? Can you increase this number to 9 or remove this check altogether?

**SDK Version**
 - Client: Kotlin
 - Version 1.11.1

**Comment by jakubuid** [comment]
Hi @stKhaDgar, at WalletConnect we follow CAIPs standards and the one responsible for aligning requirements for a namespace is CAIP-2 where the regex is defined. Have a look at: https://github.com/ChainAgnostic/CAIPs/blob/master/CAIPs/caip-2.md#syntax

**Comment by stKhaDgar** [comment]
Hey @jakubuid !

Sorry for wasting your time, I could have guessed it myself from the names of methods :)

We will think of a more concise namespace for **Everscale** blockchain!

**Comment by jakubuid** [comment]
No worries, happy to help! :)
