### ISSUE TITLE
ACCOUNT_ADDRESS_REGEX does not comply with CAIP.

### ISSUE THREAD

**Issue by stKhaDgar** [WalletConnect/WalletConnectKotlinV2#732]
**Describe the bug**
The address in the blockchain that we would like to support via **WalletConnect** contains a `:` 
_(e.g. 0:38d4c6ef92bd7ff4426eb232af3ff87bea525eff112f93eb28069e54bca89e4b)_, 
so your **[isAccountIdCAIP10Compliant](https://github.com/WalletConnect/WalletConnectKotlinV2/blob/ef6281c5b1218b03b199ddaca2207e63e1536285/androidCore/sdk/src/main/kotlin/com/walletconnect/android/internal/utils/CoreValidator.kt#L10)** function _(in the **CoreValidator** file)_ will not pass this address because the split method will return 4 lines instead of 3.

To avoid this problem, we replaced `:` with `%3A` _(encoding from the ASCII table)_, but then your regular will not resolve `%`:
`private const val ACCOUNT_ADDRESS_REGEX: String = "^([a-zA-Z0-9]{1,64})|([a-zA-Z0-9]{1,128})$"`
This code is from your **CoreValidator** file, here is a link to the line: **[CoreValidator:38](https://github.com/WalletConnect/WalletConnectKotlinV2/blob/ef6281c5b1218b03b199ddaca2207e63e1536285/androidCore/sdk/src/main/kotlin/com/walletconnect/android/internal/utils/CoreValidator.kt#L38)**

Can you please tell me what manual you used to write this regular? What I can see from the [CAIP](https://github.com/ChainAgnostic/CAIPs/blob/master/CAIPs/caip-10.md#syntax) description in the **Syntax** section regarding `account_id`- I see that their regular supports the `%` symbol - `[-.%a-zA-Z0-9]{1,128}`.

Could you add support for this symbol?
Thanks in advance for your attention!

**SDK Version**
 - Client: Kotlin
 - Version android-core:1.11.1

**Comment by Elyniss** [comment]
Hey! Thanks for the report. I believe we overlooked the regex change in Octoober 2022: https://github.com/ChainAgnostic/CAIPs/commit/222c1cd845827791416f3458930c7af80b968f48

**Comment by stKhaDgar** [comment]
@Elyniss 
👋 I am very grateful for your reply. 
Is there any timeframe when you will be able to release this fix?

> Out of curiosity may I ask what blockchain is this?
I am not sure about this, as I am just a developer trying to implement your sdk and saw an obstacle in my way.
Let me clarify and get back to you a little later with an answer.

**Comment by Elyniss** [comment]
@stKhaDgar, can I ask for a full CAIP-10 address? I want to add it to our tests.

**Comment by Elyniss** [comment]
Just to show an example of full Ethereum mainnet account: 
`eip155:1:0xe56d2b4a7cd5bac84638d4f2b78735e5815dd09e`
In your example above I'm missing `chain_id` from specs:

```
account_id:        chain_id + ":" + account_address
chain_id:          [-a-z0-9]{3,8}:[-_a-zA-Z0-9]{1,32} (See [CAIP-2][])
account_address:   [-.%a-zA-Z0-9]{1,128}
```

My understanding is that you are sending me only the `account_address` part.

**Comment by stKhaDgar** [comment]
I'm sorry, the full address would look like this:
`bc:54:0%3A38d4c6ef92bd7ff4426eb232af3ff87bea525eff112f93eb28069e54bca89e4b`

We don't have a problem with `chain_id`, so I set up the fictitious ones. The account_address is real (I already substituted `:` for `%3A`).

**Comment by stKhaDgar** [comment]
> Regarding the release, it should be available tomorrow/upcoming days

It's going to be incredibly cool! 
Thank you so much for your assistance 👍

**Comment by Elyniss** [comment]
I have to admit I scouted you out in our discord after the PR got merged 😅. The plan for release is still the same, today or Monday at worst. If something changes I will let you know
