### ISSUE TITLE
Making `Validator::validateWCUri` public

### ISSUE THREAD

**Issue by mitsinsar** [WalletConnect/WalletConnectKotlinV2#743]
In our wallet, we support both WC v1 and WC v2

To distinguish Uris, we use custom validators like;

For V1 -> We try to create `Session.Config` object with the Uri we have. If we can't create it, we assume it is invalid for v1.
For V2 -> We basically copy/pasted `Validator::validateWCUri`. If we can't create `WalletConnectUri`, we assume it is invalid for v2.

However, validator for v2 is causing a lot of duplication. Is it possible to make it public, so that we can have a function like;
`Validator.isValidWCUri(uri: String): Boolean`

Thanks!

**Comment by jasonwyatt** [comment]
+1 to this.

**Comment by TalhaAli00** [comment]
@mitsinsar @jasonwyatt 
`Core.PairingClient.validatePairingUri` has been added and will be available in the next release
