### ISSUE TITLE
The deep link of signd.app in WalletConnectKotlinV2 does not work.

### ISSUE THREAD

**Issue by sotakoyama** [WalletConnect/WalletConnectKotlinV2#772]
The deep link of signd.app in WalletConnectKotlinV2 does not work.

After selecting a chain network and trying to connect, the wallet screen is displayed, but approval dialog is not displayed.

The environment is as follows:
WalletApp: Metamask
B.O.M: 1.7.0

The only thing I did to run this sample was to set the ProjectID. Is there anything missing?

```
override fun onCreate() {
        super.onCreate()

        val serverUrl = "wss://$WALLET_CONNECT_PROD_RELAY_URL?projectId=myprojectid"

        CoreClient.initialize(
            relayServerUrl = serverUrl, connectionType = ConnectionType.AUTOMATIC, application = this,
            metaData = Core.Model.AppMetaData(
                name = "Kotlin.Responder",
                description = "Kotlin AuthSDK Responder Implementation",
                url = "kotlin.responder.walletconnect.com",
                icons = listOf("https://raw.githubusercontent.com/WalletConnect/walletconnect-assets/master/Icon/Gradient/Icon.png"),
                redirect = "kotlin-responder-wc:/request"
            )
        ) { error -> Log.e(tag(this), error.throwable.stackTraceToString()) }

        AuthClient.initialize(params = Auth.Params.Init(core = CoreClient)) { error ->
            Log.e(tag(this), error.throwable.stackTraceToString())
        }
    }
```

It may be a basic question, but I would be grateful if you could provide an answer. Thank you in advance.

![Screenshot_20230407-093855](https://user-images.githubusercontent.com/91939052/230518511-80887877-ecde-47fc-8763-e21c935d78ff.png)
![Screenshot_20230407-093849](https://user-images.githubusercontent.com/91939052/230518524-79e3883f-36e4-41e2-b0d6-04b612eae957.png)

**Comment by jakubuid** [comment]
Hey, thanks for reporting! Metamask doesn't yet support WalletConnectV2

**Comment by sotakoyama** [comment]
Thank you for providing an answer to my question.!

**Comment by sotakoyama** [comment]
Let me ask one more additional question.

I have tried Spot, Trust and Zerion in addition to Metamask.
But none of them seemed to be DeepLink enabled.

Are there any wallets that are Deeplink enabled?

**Comment by Raenar4k** [comment]
Also would like to know this. I've added project_id, yet i cannot test sample - both responder and requester do not work with Trust wallet and others.
Am i missing something?

**Comment by jakubuid** [comment]
Hey, check out this answer: https://github.com/WalletConnect/WalletConnectKotlinV2/issues/793
