### ISSUE TITLE
[Wallet] Missing redirect field on Session Proposal from Wallet

### ISSUE THREAD

**Issue by ludowkm** [WalletConnect/WalletConnectKotlinV2#792]
**Describe the bug**
On Sign.Model.SessionProposal, there is no redirect field so we can not redirect after approve proposal

**SDK Version**
 - Client: Kotlin Sign
 - Version 2.11.0

**Comment by ludowkm** [comment]
hello @jakubuid , is there any update on it ? it's also quite important because it's aim to launch the dapp from wallet after approve proposal/sign request

**Comment by jakubuid** [comment]
hello, it's released please check the newest BOM: 1.9.3
https://github.com/WalletConnect/WalletConnectKotlinV2#sdk-chart

**Comment by ludowkm** [comment]
Thank you @jakubuid , i confirm it was added!

**Comment by ludowkm** [comment]
Hello @jakubuid , i just tested but look like you just added that field to session proposal only but you did not store it.
Whenever i do request, wallet receive session request with metadata but the redirect is null, i tried to get list of activated sessions but the redirect field inside also null.
Could you please check it and make support for it, thank you!

**Comment by ludowkm** [comment]
https://github.com/WalletConnect/WalletConnectKotlinV2/pull/801/files#diff-d73f509ada9ae33a25b8d886549e381efcdc4957c0cbc3214d350bd88bc8bbe4
i saw you added storage, so i guess you just added mapper for session proposal only but not for approved session and session, could you please solve it, thank you!

**Comment by jakubuid** [comment]
@ludowkm what Dapp are you using to test this? Not every dapp is adding the redirect field on initialization to their metadata. I tested this solution with https://github.com/WalletConnect/WalletConnectKotlinV2/tree/develop/samples/dapp and I did not encounter issues that you described

**Comment by ludowkm** [comment]
@jakubuid The DApp is created by me as well, i did add redirect field in metadata when initialize SDK.
I also tested myself, i did receive the redirect field when i'm in session proposal. But i did not receive redirect field when i'm in session request (redirect field in metadata is null, event try to find session in list of activated sessions, the redirect field also null)
Could you please have a look on session request, don't test with session proposal only.

**Comment by jakubuid** [comment]
So I wasn't able to reproduce it following your steps and using [develop/samples/dapp](https://github.com/WalletConnect/WalletConnectKotlinV2/tree/develop/samples/dapp?rgh-link-date=2023-05-10T09%3A18%3A04Z). Redirect field was never null neither in session request in metadata nor in active session from the list.

Can you share please how you initialize your Dapp?
Are your apps (Dapp and Wallet) separated instances?

**Comment by john990** [comment]
I also encountered the same problem, in ```WalletDelegate.onSessionRequest``` method, param ``Sign.Model.SessionRequest``` didn't contain redirect.

Here is the code of how we create the connection:
https://github.com/Outblock/fcl-android/blob/main/fcl/src/main/java/io/outblock/fcl/strategies/walletconnect/WalletConnect.kt#L59-L88
