### ISSUE TITLE
Sample Auth Requester/Responder does not work with external apps, but Web example does

### ISSUE THREAD

**Issue by Raenar4k** [WalletConnect/WalletConnectKotlinV2#793]
**Describe the bug**
I have built sample with our project id. I tried to use requester / responder with external apps such as Trust Wallet. They don't have any reaction after scanning QR code or responder does not have any reaction after scanning QR.

But, Trust Wallet seems to respond to QR code generated by Web sample app, such as listed here:
https://github.com/WalletConnect/web-examples

When using https://react-app.walletconnect.com/  sample app Trust Wallet does display it after scanning QR code.

Same does not happen when using Auth Requester sample.

Maybe i am missing something obvious? New to this thing, so any feedback is welcome :)

**SDK Version**
 - Client: Kotlin

- Versions of dependencies as listed in that commit
const val BOM_VERSION = "1.8.0"
const val FOUNDATION_VERSION = "1.7.0"
const val CORE_VERSION = "1.13.0"
const val SIGN_VERSION = "2.11.0"
const val SYNC_VERSION = "1.0.0-alpha01"
const val AUTH_VERSION = "1.11.0"
const val CHAT_VERSION = "1.0.0-beta05"
const val WEB_3_WALLET = "1.6.0"
const val WEB_3_INBOX = "1.0.0-alpha05"

**To Reproduce**
1. Take current sample (commit 36ad65313ecc0cde485b1633d566626f047ab34e )
2. Build AUTH Requester/Responder with your project id
3. Try to connect with any external app 

**Expected behavior**
Connection works, external app have some reaction to it

**Comment by Raenar4k** [comment]
Hey, thanks for reply. Tried Spot Wallet, and it does react to QR code or deeplink, so it is a plus.
However, is this reaction expected? As it says that this QR code is not supported.

Also tried deeplink with responder, and it does not react to it at all.

https://user-images.githubusercontent.com/13849790/231756783-8791b34b-eca3-4d47-b40a-b0f2975903c1.mp4

https://user-images.githubusercontent.com/13849790/231756734-d603a425-1667-4104-b7ab-b9dafa1b0d6d.mp4

**Comment by Raenar4k** [comment]
Hello. Any updates?
We want to integrate wallet connect, but so far only V1 was working. And we don't want to start implementing v1, since it will be discontinued in 2 months.

Before we start any integration of V2, I want to test sample app to see how it works with common wallets. So far both iOS and Android samples don't work properly with our project id. @jakubuid

**Comment by jakubuid** [comment]
Thanks for your patience 🙏  We've been working on some other urgent issues, but now I'll investigate this asap since our top priority is getting all wallets on v2.
As far as Auth, Zerion, Spot and BitKeep support it, you can test it using our playground dapp: https://react-auth-dapp.vercel.app/

I'll look into deep-link issue.


_So far both iOS and Android samples don't work properly with our project id_ - can you elaborate on this?

**Comment by Raenar4k** [comment]
Thanks for response!

> As far as Auth, Zerion, Spot and BitKeep support it, you can test it using our playground dapp: https://react-auth-dapp.vercel.app/

Tested with SpotWallet. It says that this is not a valid QR code. Same result as video i posted above. Is this expected?

> So far both iOS and Android samples don't work properly with our project id - can you elaborate on this?
iOS team managed to get reaction from wallet and see our app. But after approving nothing happens.
It is very similar to issue reported here:
https://discord.com/channels/492410046307631105/1103433762156589127

> I am able to successfully redirect to the wallet app where I can see the modal which lists down all the possible things I am granting request for. But after I click on approve and go back to my app, I don't receive any response in the sessionResponsePublisher

**Comment by jakubuid** [comment]
Make sure that your SpotWallet is up to date. I've tested with 4.76.2 and it works without issues.
Regarding the iOS issue, I suggest creating an issue here: https://github.com/WalletConnect/WalletConnectSwiftV2/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Comment by Raenar4k** [comment]
@jakubuid Here is the test with SpotWallet 4.76.2.
After using deeplink it says "Not a WalletConnect valid QR code".

Is this expected?
I expect link to be recognized and some approval of our app shown in wallet.

As far as i know, our iOS team managed to do this with V1 but not with V2.
(iOS - But even after approving there is no more communication, so we dont get any data)

https://user-images.githubusercontent.com/13849790/236460205-da5feae3-f370-4840-9cde-c32962f2b601.mp4

**Comment by Raenar4k** [comment]
@jakubuid tried SpotWallet on iOS and it connected to Android sample. Address is shown and balance, after approval.

But SpotWallet on Android does not connect to android requester sample on same device by deeplink.
Tried Zerion, found on this page https://explorer.walletconnect.com/?type=wallet&version=2

Same thing - 0 reaction.

**Comment by Raenar4k** [comment]
Tested wallets listed that support WalletConnect V2
 https://explorer.walletconnect.com/?type=wallet&version=2
 
 So far none of them worked by deeplink. Some do not react at all, some show infinite loading.

![wallets](https://user-images.githubusercontent.com/13849790/236471040-fd61eb09-e8d2-47ad-8cc2-1eac3d615c2f.jpeg)

**Comment by jakubuid** [comment]
Thanks for all those examples. It's very helpful, I'll let you know once we have it resolved!

**Comment by jakubuid** [comment]
Trust doesn't support Auth yet
Besides that Spot does and it looks like an issue on the requester sample, I'm investigating

**Comment by Raenar4k** [comment]
@jakubuid Thanks for response. 
So issue was in sdk itself? 
And once wallets update to new version of SDK sample should work correctly?

**Comment by jakubuid** [comment]
Yes the issues was in the SDK
Yes, once they update the discussed issues should be resolved. We already notified them
To test it you can use those:

- https://github.com/WalletConnect/WalletConnectKotlinV2/tree/develop/samples/wallet
- https://github.com/WalletConnect/WalletConnectKotlinV2/tree/develop/auth/requester
-  https://github.com/WalletConnect/WalletConnectKotlinV2/tree/develop/samples/dapp
