### ISSUE TITLE
Q: Is there a way to sign transaction with your SDK?

### ISSUE THREAD

**Issue by y9san9** [WalletConnect/WalletConnectKotlinV2#80]
I want to use wallet connect in my App, so user will not have to enter his credentials to make the app work, but instead they can use wallet connect to sign transactions.

**Comment by jakobuid** [comment]
Hey, could you add more specifics what you what to achieve?

**Comment by y9san9** [comment]
Something like this: https://github.com/pink-room/walletconnectkit-android/issues/7

**Comment by jakobuid** [comment]
Yes, this is possible.  You can sign every message that you want.
