### ISSUE TITLE
Connect to wallet after pairing is established

### ISSUE THREAD

**Issue by TalhaAli00** [WalletConnect/WalletConnectKotlinV2#828]
Once the dapp has a pairing (either by generating a new pairing or using an existing pairing), the Dapp will need to generate a `Sign.Params.Connect` object and pass it to the `SignClient.connect`
method and passed to `SignClient.connect` to connect to a wallet

The `Sign.Params.Connect` will need to contain

* a map of type `Map<String, Sign.Model.Namespace.Proposal>` for `requiredNamespaces`
* a map of type `Map<String, Sign.Model.Namespace.Proposal>` for `optionalNamespaces`
* a map of type `Map<String, String` for `properties`
* the selected pairing for `pairing`
  (Logic can be copied from the `ConnectViewModel` file in the Sign:Dapp sample)

Once the wallet responds with either an approval or rejection of the session proposal, the DappDelegate will emit an event on the `onSessionApproved` or `onSessionRejected` methods respectively.

* On approval, the dapp should navigate to an "Selected Session" screen similar to the `SessionFragment` in the Sign:Dapp sample.
* On rejection, the dapp should navigate the user back to screen to the chain selection screen

<br>

Along with the screen to select chains, the dapp will also need another screen available at the same navigation level. This new "All Active Sessions" screen will allow users to see a list of all the active sessions
available through the `SignClient.getListOfActiveSessions` which will be displayed as a list. This method is blocking and must be called from a background thread. This list of active sessions must always be up to date. When
the `DappDelegate.onSessionDelete` is emitted, the dapp should refresh the list of active sessions.

Each item in the list will show the wallet name and the wallet icon. 

## <b>If at any point there's an error, log it to the console and to Firebase</b>

**Comment by kacperoak** [comment]
Closing. Already done in sample dapp
