### ISSUE TITLE
Select account from Active Session

### ISSUE THREAD

**Issue by TalhaAli00** [WalletConnect/WalletConnectKotlinV2#830]
When a selection of an account is made from the "Selected Session" screen, the dapp should navigate to a new screen to show details about the selected account similar to the `SelectedAccountFragment`.
The screen should show the chain icon, account name, account address, and a list of methods associated with the selected account's namespace.

Clicking on any of the methods should trigger a call to `SignClient.request`. An example of this can be found in Sign:Dapp "SelectedAccountViewModel". After the request has been sent, try to deeplink
into the wallet by using the redirect URI from the active session if it exists
Once the request has been responded to and the DappDelegate triggers an event for either approval or rejection of the request, this screen should show a dialog based on the event.

* If the DappDelegate emits an event from `onSessionRequestResponse` with a `Sign.Model.SessionRequestResponse.result` of type `JsonRpcResult`, then emit the object's `result` field in a modal to the
  user. The modal should have a button to close the modal.
* If the DappDelegate emits an event from `onSessionRequestResponse` with a `Sign.Model.SessionRequestResponse.result` of type `JsonRpcError`, then emit the object's `message` field in a modal to the
  user. The modal should have a button to close the modal.

This screen should also listen for the following methods of the DappDelegate:
* The `onSessionDelete` event will navigate the user to the root of the navigation graph.
* The `onSessionUpdate` event will need to fetch the latest namespace information and update the UI accordingly.
* The `onSessionEvent` event will show a toast/snackbar to the user that there was an update to the list of events

## <b>If at any point there's an error, log it to the console and to Firebase</b>

**Comment by kacperoak** [comment]
Closing. Merged in: https://github.com/WalletConnect/WalletConnectKotlinV2/pull/833
