### ISSUE TITLE
Ping works only for first time

### ISSUE THREAD

**Issue by rafaelekol** [WalletConnect/WalletConnectKotlinV2#84]
When I call ping method, it returns answer only for the first time. Subsequent ping don't return answer or error. 
I use Ping to check for session availability when network connection goes offline then back online.

**Comment by jakobuid** [comment]
Hey, thanks for reporting.
Do you use ping in the wallet sample app  or you have your own integration of sdk?

The current sample app implementation is not yet align with the newest sdk release, and yes indeed with the current sample app ping message is shown only once. SDK returns ping answer every-time, however there is a bug in sample app that causes issue described by you.

We work to improve the sample app experience to provide WalletConnect integration standard.

**Comment by rafaelekol** [comment]
I use sample app as reference. Thus my app also not getting subsequent ping responses. By the way I use `ping`  also for reconnecting existing peer. Is it the right method to use for this purpose?
I tried to use `connect` method to reconnect existing peer session, but it gives error.

**Comment by jakobuid** [comment]
Couple things:
- ping will return result only when another peer is online
- Could you please elaborate: `I use ping also for reconnecting existing peer` ?
- What error did you get? All session are stored in the sdk's database. So when you kill and launch application, all sessions are resubscribed automatically.

**Comment by rafaelekol** [comment]
My case is like this. I have connected session, 
then I turn off network connection on the phone, 
press disconnect button in dApp on PC,
turn on network connection back.
Now I need to know if I still have session. I tried calling `WalletConnectClient.getListOfSettledSessions()` and I tried to ping this topic, but WC client still not knowing that dApp already killed this session.
Only after app kill and cold start WC client removes this killed session from list.

**Comment by jakobuid** [comment]
Thanks for reporting.
I recreated your flow and observed the same behaviour.
We're still in beta and such issues helps to increase the stability of sdk.
We're going to fix it.
Reported issue: https://github.com/WalletConnect/WalletConnectKotlinV2/issues/86

**Comment by chadyj** [comment]
Fixed in https://github.com/WalletConnect/WalletConnectKotlinV2/issues/86
