### ISSUE TITLE
Not pairing on first run after app data clean.

### ISSUE THREAD

**Issue by rafaelekol** [WalletConnect/WalletConnectKotlinV2#85]
When I clear all data in app,  and launch Wallet demo app again it's not pairing. I click scan QR button, it scans but then nothing happens. Then I need to kill app, and launch it again to make Pair work.

**Comment by jakobuid** [comment]
Thanks for reporting.
I'll have a deeper look on that.

**Comment by jakobuid** [comment]
Created issue: https://github.com/WalletConnect/WalletConnectKotlinV2/issues/89

**Comment by jakobuid** [comment]
Hey, check our latest beta-100 release and test it with https://react-app.walletconnect.com/. There've been many changes and fixes.
