### ISSUE TITLE
[feature] WalletConnectModal: Add custom headers to explorer-api request

### ISSUE THREAD

**Issue by ignaciosantise** [WalletConnect/WalletConnectKotlinV2#917]
### What problem does this new feature solve?

Adds `user-agent` and `referer` headers in explorer-api requests

### Describe the solution you'd like

* `user-agent` that follows the pattern `<web3modal version>/<core sdk version>/<operating system>`
* `referer` containing the `name` provided in the sdk metadata (with no spaces)

example:
```js
headers: {
 user-agent: 'w3m-android-1.0.0/kotlin-1.5.7/android-31',
 referer: 'WCDapp'
}
```

**Comment by TalhaAli00** [comment]
Hey @ignaciosantise, I just want to make sure that the `referer` field is just the app name that's registered with WC correct?

**Comment by ignaciosantise** [comment]
As discussed in Slack, we will use the `name` property from the MetaData.
