### ISSUE TITLE
Switch to JUnit 4

### ISSUE THREAD

**Issue by TalhaAli00** [WalletConnect/WalletConnectKotlinV2#947]
Remove JUnit 5 and move all tests to use JUnit 4

Google does not currently support JUnit 5 natively. We've had JUnit 5 for almost 2 years and there is still no indication that JUnit 5 will be added to the test suite anytime soon.

**Comment by Elyniss** [comment]
Switching to JUnit4 enables instrumentation tests on older APIs, we might want to update intrsumented tests ci matrix once we migrate
