### ISSUE TITLE
JSON-RPC Request has invalid publish params

### ISSUE THREAD

**Issue by gityms123** [WalletConnect/WalletConnectKotlinV2#96]
Hello I follow the git code, but when calling the WalletConnectClient.pair method it returns
java.lang.Throwable: Error code: -32000; Error message: JSON-RPC Request has invalid publish params

**Comment by jakobuid** [comment]
What dApp are you trying to connect with?

**Comment by gityms123** [comment]
Thank  That's stellarterm and stellarx

**Comment by jakobuid** [comment]
Hey, check out lates beta-100 release and test it with https://react-app.walletconnect.com/. There've been many changes and fixes.
