### ISSUE TITLE
On responding Session Request there is no success callback 

### ISSUE THREAD

**Issue by rafaelekol** [WalletConnect/WalletConnectKotlinV2#97]
I use this method to get list of pending requests `WalletConnectClient.getJsonRpcHistory(topic)`
After I process request by responding or rejecting I need to refresh my list of session requests. But currently I didn't find method to get signal when WalletConnect local list is updated.

**Comment by jakobuid** [comment]
Hi. We are introducing an internal protocol breaking changes. In addition, we change the way of exposing the requests. I will be allowed to get all pending requests between peers.
Question: Exposed list of pending request is enough for you? Or you will need the whole history of all session requests between dapp and the wallet?

**Comment by rafaelekol** [comment]
In our case List of Pending Requests is enough.
