### ISSUE TITLE
pair no callback

### ISSUE THREAD

**Issue by gityms123** [WalletConnect/WalletConnectKotlinV2#99]
I download the source code of git and run it directly. When I call the WalletConnectClient.pair method,no success callback，Error and no error callback. Is it a problem with the relay service, do I need to build my own relay service?

**Comment by rafaelekol** [comment]
I have similar problem. In my case to reproduce it I open https://react-app.walletconnect.com/, start new connection, scan QR code from wallet. After getting information from wallet connect dApp I press back button in wallet and try to scan QR code again. This time pair method not responding, not giving `error` or `success`.

**Comment by jakobuid** [comment]
Hey, thanks for reporting.
This issue is know on our side. We're working on the protocol improvements under the hood, so reported issue will be gone.
Wait for the upcoming v2.0-rc.
